/*
Copyright DepinSubnet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HTTPOptionsApplyConfiguration represents a declarative configuration of the HTTPOptions type for use
// with apply.
type HTTPOptionsApplyConfiguration struct {
	MaxBodySize *int     `json:"max_body_size,omitempty"`
	ReadTimeout *int     `json:"read_timeout,omitempty"`
	SendTimeout *int     `json:"send_timeout,omitempty"`
	NextTries   *int     `json:"next_tries,omitempty"`
	NextTimeout *int     `json:"next_timeout,omitempty"`
	NextCases   []string `json:"next_cases,omitempty"`
}

// HTTPOptionsApplyConfiguration constructs a declarative configuration of the HTTPOptions type for use with
// apply.
func HTTPOptions() *HTTPOptionsApplyConfiguration {
	return &HTTPOptionsApplyConfiguration{}
}

// WithMaxBodySize sets the MaxBodySize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxBodySize field is set to the value of the last call.
func (b *HTTPOptionsApplyConfiguration) WithMaxBodySize(value int) *HTTPOptionsApplyConfiguration {
	b.MaxBodySize = &value
	return b
}

// WithReadTimeout sets the ReadTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadTimeout field is set to the value of the last call.
func (b *HTTPOptionsApplyConfiguration) WithReadTimeout(value int) *HTTPOptionsApplyConfiguration {
	b.ReadTimeout = &value
	return b
}

// WithSendTimeout sets the SendTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SendTimeout field is set to the value of the last call.
func (b *HTTPOptionsApplyConfiguration) WithSendTimeout(value int) *HTTPOptionsApplyConfiguration {
	b.SendTimeout = &value
	return b
}

// WithNextTries sets the NextTries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextTries field is set to the value of the last call.
func (b *HTTPOptionsApplyConfiguration) WithNextTries(value int) *HTTPOptionsApplyConfiguration {
	b.NextTries = &value
	return b
}

// WithNextTimeout sets the NextTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextTimeout field is set to the value of the last call.
func (b *HTTPOptionsApplyConfiguration) WithNextTimeout(value int) *HTTPOptionsApplyConfiguration {
	b.NextTimeout = &value
	return b
}

// WithNextCases adds the given value to the NextCases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NextCases field.
func (b *HTTPOptionsApplyConfiguration) WithNextCases(values ...string) *HTTPOptionsApplyConfiguration {
	for i := range values {
		b.NextCases = append(b.NextCases, values[i])
	}
	return b
}
