/*
Copyright DepinSubnet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ManifestSpecApplyConfiguration represents a declarative configuration of the ManifestSpec type for use
// with apply.
type ManifestSpecApplyConfiguration struct {
	Lease *LeaseSpecApplyConfiguration `json:"lease,omitempty"`
	Group *GroupSpecApplyConfiguration `json:"group,omitempty"`
}

// ManifestSpecApplyConfiguration constructs a declarative configuration of the ManifestSpec type for use with
// apply.
func ManifestSpec() *ManifestSpecApplyConfiguration {
	return &ManifestSpecApplyConfiguration{}
}

// WithLease sets the Lease field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lease field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithLease(value *LeaseSpecApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Lease = value
	return b
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ManifestSpecApplyConfiguration) WithGroup(value *GroupSpecApplyConfiguration) *ManifestSpecApplyConfiguration {
	b.Group = value
	return b
}
