/*
Copyright The Subnet Node Authors.

Licensed under the he License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apissubnetnodev1 "github.com/unicornultrafoundation/subnet-node/pkg/k8s/apis/subnet.node/v1"
	versioned "github.com/unicornultrafoundation/subnet-node/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/unicornultrafoundation/subnet-node/pkg/k8s/client/informers/externalversions/internalinterfaces"
	subnetnodev1 "github.com/unicornultrafoundation/subnet-node/pkg/k8s/client/listers/subnet.node/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ProviderLeasedIPInformer provides access to a shared informer and lister for
// ProviderLeasedIPs.
type ProviderLeasedIPInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() subnetnodev1.ProviderLeasedIPLister
}

type providerLeasedIPInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewProviderLeasedIPInformer constructs a new informer for ProviderLeasedIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProviderLeasedIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProviderLeasedIPInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredProviderLeasedIPInformer constructs a new informer for ProviderLeasedIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProviderLeasedIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubnetV1().ProviderLeasedIPs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubnetV1().ProviderLeasedIPs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubnetV1().ProviderLeasedIPs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubnetV1().ProviderLeasedIPs(namespace).Watch(ctx, options)
			},
		},
		&apissubnetnodev1.ProviderLeasedIP{},
		resyncPeriod,
		indexers,
	)
}

func (f *providerLeasedIPInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProviderLeasedIPInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *providerLeasedIPInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apissubnetnodev1.ProviderLeasedIP{}, f.defaultInformer)
}

func (f *providerLeasedIPInformer) Lister() subnetnodev1.ProviderLeasedIPLister {
	return subnetnodev1.NewProviderLeasedIPLister(f.Informer().GetIndexer())
}
