version: "2.0"
services:
  web:
    image: hashicorp/http-echo
    command: ["/http-echo", "-text", "Hello from http-echo!"]
    expose:
      - port: 5678
        as: 80
        to:
          - global: true
    params:
      health:
        readiness:
          http:
            path: /
            port: 5678
          initial_delay_seconds: 5
          period_seconds: 10
          timeout_seconds: 5
          success_threshold: 1
          failure_threshold: 3
        liveness:
          http:
            path: /
            port: 5678
          initial_delay_seconds: 15
          period_seconds: 10
          timeout_seconds: 5
          success_threshold: 1
          failure_threshold: 3
    resources:
      cpu:
        units:
          value: 1
          unit: m
      memory:
        size:
          value: 1024
          unit: Mi
      storage:
        size:
          value: 1024
          unit: Mi

profiles:
  compute:
    default:
      resources:
        cpu:
          request: 1
          limit: 2
        memory:
          request: 1
          limit: 2
        storage:
          - size: 0
  placement:
    default:
      attributes:
        region: us-west
      pricing:
        cpu:
          denom: u2u
          amount: 1000
        memory:
          denom: u2u
          amount: 500
        storage:
          denom: u2u
          amount: 200

deployment:
  default:
    profile: default
    count: 1

endpoints:
  echo:
    kind: web
