// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: audit/v1/audit.proto

package v1

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_unicornultrafoundation_subnet_node_proto_subnet_k8s_base_v1 "github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/base/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Provider stores owner auditor and attributes details
type Provider struct {
	Owner                string                                                                            `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	Auditor              string                                                                            `protobuf:"bytes,2,opt,name=auditor,proto3" json:"auditor" yaml:"auditor"`
	Attributes           github_com_unicornultrafoundation_subnet_node_proto_subnet_k8s_base_v1.Attributes `protobuf:"bytes,4,rep,name=attributes,proto3,castrepeated=github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/base/v1.Attributes" json:"attributes" yaml:"attributes"`
	XXX_NoUnkeyedLiteral struct{}                                                                          `json:"-"`
	XXX_unrecognized     []byte                                                                            `json:"-"`
	XXX_sizecache        int32                                                                             `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{0}
}
func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Provider) GetAuditor() string {
	if m != nil {
		return m.Auditor
	}
	return ""
}

func (m *Provider) GetAttributes() github_com_unicornultrafoundation_subnet_node_proto_subnet_k8s_base_v1.Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// Attributes
type AuditedAttributes struct {
	Owner                string                                                                            `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	Auditor              string                                                                            `protobuf:"bytes,2,opt,name=auditor,proto3" json:"auditor" yaml:"auditor"`
	Attributes           github_com_unicornultrafoundation_subnet_node_proto_subnet_k8s_base_v1.Attributes `protobuf:"bytes,3,rep,name=attributes,proto3,castrepeated=github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/base/v1.Attributes" json:"attributes" yaml:"attributes"`
	XXX_NoUnkeyedLiteral struct{}                                                                          `json:"-"`
	XXX_unrecognized     []byte                                                                            `json:"-"`
	XXX_sizecache        int32                                                                             `json:"-"`
}

func (m *AuditedAttributes) Reset()         { *m = AuditedAttributes{} }
func (m *AuditedAttributes) String() string { return proto.CompactTextString(m) }
func (*AuditedAttributes) ProtoMessage()    {}
func (*AuditedAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{1}
}
func (m *AuditedAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditedAttributes.Unmarshal(m, b)
}
func (m *AuditedAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditedAttributes.Marshal(b, m, deterministic)
}
func (m *AuditedAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditedAttributes.Merge(m, src)
}
func (m *AuditedAttributes) XXX_Size() int {
	return xxx_messageInfo_AuditedAttributes.Size(m)
}
func (m *AuditedAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditedAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_AuditedAttributes proto.InternalMessageInfo

func (m *AuditedAttributes) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AuditedAttributes) GetAuditor() string {
	if m != nil {
		return m.Auditor
	}
	return ""
}

func (m *AuditedAttributes) GetAttributes() github_com_unicornultrafoundation_subnet_node_proto_subnet_k8s_base_v1.Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// AttributesResponse represents details of deployment along with group details
type AttributesResponse struct {
	Attributes           []AuditedAttributes `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes" yaml:"attributes"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AttributesResponse) Reset()         { *m = AttributesResponse{} }
func (m *AttributesResponse) String() string { return proto.CompactTextString(m) }
func (*AttributesResponse) ProtoMessage()    {}
func (*AttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{2}
}
func (m *AttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributesResponse.Unmarshal(m, b)
}
func (m *AttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributesResponse.Marshal(b, m, deterministic)
}
func (m *AttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributesResponse.Merge(m, src)
}
func (m *AttributesResponse) XXX_Size() int {
	return xxx_messageInfo_AttributesResponse.Size(m)
}
func (m *AttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttributesResponse proto.InternalMessageInfo

func (m *AttributesResponse) GetAttributes() []AuditedAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// AttributesFilters defines filters used to filter deployments
type AttributesFilters struct {
	Auditors             []string `protobuf:"bytes,1,rep,name=auditors,proto3" json:"auditors" yaml:"auditors"`
	Owners               []string `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners" yaml:"owners"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributesFilters) Reset()         { *m = AttributesFilters{} }
func (m *AttributesFilters) String() string { return proto.CompactTextString(m) }
func (*AttributesFilters) ProtoMessage()    {}
func (*AttributesFilters) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{3}
}
func (m *AttributesFilters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributesFilters.Unmarshal(m, b)
}
func (m *AttributesFilters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributesFilters.Marshal(b, m, deterministic)
}
func (m *AttributesFilters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributesFilters.Merge(m, src)
}
func (m *AttributesFilters) XXX_Size() int {
	return xxx_messageInfo_AttributesFilters.Size(m)
}
func (m *AttributesFilters) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributesFilters.DiscardUnknown(m)
}

var xxx_messageInfo_AttributesFilters proto.InternalMessageInfo

func (m *AttributesFilters) GetAuditors() []string {
	if m != nil {
		return m.Auditors
	}
	return nil
}

func (m *AttributesFilters) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

// MsgSignProviderAttributes defines an SDK message for signing a provider attributes
type MsgSignProviderAttributes struct {
	Owner                string                                                                            `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	Auditor              string                                                                            `protobuf:"bytes,2,opt,name=auditor,proto3" json:"auditor" yaml:"auditor"`
	Attributes           github_com_unicornultrafoundation_subnet_node_proto_subnet_k8s_base_v1.Attributes `protobuf:"bytes,3,rep,name=attributes,proto3,castrepeated=github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/base/v1.Attributes" json:"attributes" yaml:"attributes"`
	XXX_NoUnkeyedLiteral struct{}                                                                          `json:"-"`
	XXX_unrecognized     []byte                                                                            `json:"-"`
	XXX_sizecache        int32                                                                             `json:"-"`
}

func (m *MsgSignProviderAttributes) Reset()         { *m = MsgSignProviderAttributes{} }
func (m *MsgSignProviderAttributes) String() string { return proto.CompactTextString(m) }
func (*MsgSignProviderAttributes) ProtoMessage()    {}
func (*MsgSignProviderAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{4}
}
func (m *MsgSignProviderAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSignProviderAttributes.Unmarshal(m, b)
}
func (m *MsgSignProviderAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSignProviderAttributes.Marshal(b, m, deterministic)
}
func (m *MsgSignProviderAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignProviderAttributes.Merge(m, src)
}
func (m *MsgSignProviderAttributes) XXX_Size() int {
	return xxx_messageInfo_MsgSignProviderAttributes.Size(m)
}
func (m *MsgSignProviderAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignProviderAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignProviderAttributes proto.InternalMessageInfo

func (m *MsgSignProviderAttributes) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgSignProviderAttributes) GetAuditor() string {
	if m != nil {
		return m.Auditor
	}
	return ""
}

func (m *MsgSignProviderAttributes) GetAttributes() github_com_unicornultrafoundation_subnet_node_proto_subnet_k8s_base_v1.Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// MsgSignProviderAttributesResponse defines the Msg/CreateProvider response type.
type MsgSignProviderAttributesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSignProviderAttributesResponse) Reset()         { *m = MsgSignProviderAttributesResponse{} }
func (m *MsgSignProviderAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSignProviderAttributesResponse) ProtoMessage()    {}
func (*MsgSignProviderAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{5}
}
func (m *MsgSignProviderAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSignProviderAttributesResponse.Unmarshal(m, b)
}
func (m *MsgSignProviderAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSignProviderAttributesResponse.Marshal(b, m, deterministic)
}
func (m *MsgSignProviderAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignProviderAttributesResponse.Merge(m, src)
}
func (m *MsgSignProviderAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSignProviderAttributesResponse.Size(m)
}
func (m *MsgSignProviderAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignProviderAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignProviderAttributesResponse proto.InternalMessageInfo

// MsgDeleteProviderAttributes defined the Msg/DeleteProviderAttributes
type MsgDeleteProviderAttributes struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	Auditor              string   `protobuf:"bytes,2,opt,name=auditor,proto3" json:"auditor" yaml:"auditor"`
	Keys                 []string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys" yaml:"keys"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeleteProviderAttributes) Reset()         { *m = MsgDeleteProviderAttributes{} }
func (m *MsgDeleteProviderAttributes) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteProviderAttributes) ProtoMessage()    {}
func (*MsgDeleteProviderAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{6}
}
func (m *MsgDeleteProviderAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeleteProviderAttributes.Unmarshal(m, b)
}
func (m *MsgDeleteProviderAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeleteProviderAttributes.Marshal(b, m, deterministic)
}
func (m *MsgDeleteProviderAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteProviderAttributes.Merge(m, src)
}
func (m *MsgDeleteProviderAttributes) XXX_Size() int {
	return xxx_messageInfo_MsgDeleteProviderAttributes.Size(m)
}
func (m *MsgDeleteProviderAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteProviderAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteProviderAttributes proto.InternalMessageInfo

func (m *MsgDeleteProviderAttributes) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgDeleteProviderAttributes) GetAuditor() string {
	if m != nil {
		return m.Auditor
	}
	return ""
}

func (m *MsgDeleteProviderAttributes) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// MsgDeleteProviderAttributesResponse defines the Msg/ProviderAttributes response type.
type MsgDeleteProviderAttributesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeleteProviderAttributesResponse) Reset()         { *m = MsgDeleteProviderAttributesResponse{} }
func (m *MsgDeleteProviderAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteProviderAttributesResponse) ProtoMessage()    {}
func (*MsgDeleteProviderAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16d867259c094f3a, []int{7}
}
func (m *MsgDeleteProviderAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeleteProviderAttributesResponse.Unmarshal(m, b)
}
func (m *MsgDeleteProviderAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeleteProviderAttributesResponse.Marshal(b, m, deterministic)
}
func (m *MsgDeleteProviderAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteProviderAttributesResponse.Merge(m, src)
}
func (m *MsgDeleteProviderAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_MsgDeleteProviderAttributesResponse.Size(m)
}
func (m *MsgDeleteProviderAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteProviderAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteProviderAttributesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Provider)(nil), "subnet.k8s.audit.v1.Provider")
	proto.RegisterType((*AuditedAttributes)(nil), "subnet.k8s.audit.v1.AuditedAttributes")
	proto.RegisterType((*AttributesResponse)(nil), "subnet.k8s.audit.v1.AttributesResponse")
	proto.RegisterType((*AttributesFilters)(nil), "subnet.k8s.audit.v1.AttributesFilters")
	proto.RegisterType((*MsgSignProviderAttributes)(nil), "subnet.k8s.audit.v1.MsgSignProviderAttributes")
	proto.RegisterType((*MsgSignProviderAttributesResponse)(nil), "subnet.k8s.audit.v1.MsgSignProviderAttributesResponse")
	proto.RegisterType((*MsgDeleteProviderAttributes)(nil), "subnet.k8s.audit.v1.MsgDeleteProviderAttributes")
	proto.RegisterType((*MsgDeleteProviderAttributesResponse)(nil), "subnet.k8s.audit.v1.MsgDeleteProviderAttributesResponse")
}

func init() { proto.RegisterFile("audit/v1/audit.proto", fileDescriptor_16d867259c094f3a) }

var fileDescriptor_16d867259c094f3a = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0x6e, 0xb2, 0x6b, 0xdd, 0x9d, 0xfa, 0x83, 0x8d, 0xc5, 0xa6, 0x5b, 0xca, 0xd4, 0x29, 0x6a,
	0x41, 0x9c, 0xb8, 0x2d, 0xe8, 0x52, 0x4f, 0x0d, 0xa2, 0x78, 0x58, 0xd0, 0x78, 0xf3, 0x96, 0x34,
	0x63, 0x0c, 0xbb, 0xcd, 0x94, 0xcc, 0x64, 0xa5, 0xe0, 0xc1, 0x93, 0x57, 0xf1, 0xe6, 0xb1, 0x67,
	0x8f, 0x1e, 0xf5, 0x2c, 0xe8, 0x3f, 0x31, 0x5e, 0x25, 0xc7, 0xfc, 0x05, 0xb2, 0x33, 0x49, 0x36,
	0xc5, 0x46, 0x5c, 0x3c, 0x2c, 0x42, 0x6f, 0x99, 0xef, 0xbd, 0x6f, 0xde, 0x7b, 0xdf, 0x7c, 0x8f,
	0x80, 0x65, 0x37, 0xf1, 0x43, 0x6e, 0x8d, 0x7b, 0x96, 0xfc, 0xc0, 0x87, 0x31, 0xe5, 0xd4, 0xb8,
	0xc2, 0x12, 0x2f, 0x22, 0x1c, 0x0f, 0xfb, 0x0c, 0x2b, 0x7c, 0xdc, 0xeb, 0x2e, 0x07, 0x34, 0xa0,
	0x32, 0x6e, 0x4d, 0xbe, 0x54, 0x6a, 0x77, 0xc5, 0x73, 0x19, 0x91, 0x7c, 0xce, 0xe3, 0xd0, 0x4b,
	0x38, 0x51, 0x01, 0xf4, 0x49, 0x07, 0xad, 0x27, 0x31, 0x1d, 0x87, 0x3e, 0x89, 0x0d, 0x0b, 0x9c,
	0xa3, 0xaf, 0x22, 0x12, 0x9b, 0xda, 0x86, 0xb6, 0xd5, 0xb6, 0x57, 0x53, 0x01, 0x15, 0x90, 0x09,
	0x78, 0xe1, 0xc8, 0x3d, 0x18, 0xed, 0x22, 0x79, 0x44, 0x8e, 0x82, 0x8d, 0x7b, 0xe0, 0xbc, 0x2c,
	0x4c, 0x63, 0x53, 0x97, 0x94, 0xf5, 0x54, 0xc0, 0x02, 0xca, 0x04, 0xbc, 0xa4, 0x48, 0x39, 0x80,
	0x9c, 0x22, 0x64, 0x7c, 0xd1, 0x00, 0x28, 0x5b, 0x61, 0x66, 0x73, 0xa3, 0xb1, 0xb5, 0xb4, 0xbd,
	0x8e, 0x2b, 0x03, 0x4d, 0x1a, 0xc6, 0xe3, 0x1e, 0xde, 0x2b, 0xb2, 0xec, 0xd7, 0xdf, 0x04, 0x5c,
	0x48, 0x05, 0xac, 0x10, 0x33, 0x01, 0x3b, 0x79, 0x89, 0x12, 0x43, 0x1f, 0x7f, 0xc0, 0xa7, 0x41,
	0xc8, 0x5f, 0x26, 0x1e, 0xde, 0xa7, 0x07, 0x56, 0x12, 0x85, 0xfb, 0x34, 0x8e, 0x92, 0x11, 0x8f,
	0xdd, 0x17, 0x34, 0x89, 0x7c, 0x97, 0x87, 0x34, 0xb2, 0x54, 0xa9, 0xdb, 0x11, 0xf5, 0x89, 0xa5,
	0xe4, 0x52, 0x88, 0x35, 0xec, 0x33, 0x2b, 0x57, 0x6b, 0x5a, 0x9c, 0x39, 0x95, 0xaa, 0xe8, 0xab,
	0x0e, 0x3a, 0x7b, 0x93, 0x49, 0x88, 0x3f, 0xcd, 0x98, 0x9f, 0x7a, 0x8d, 0xff, 0x4a, 0xbd, 0xdd,
	0xd6, 0x87, 0x63, 0xa8, 0xfd, 0x3c, 0x86, 0x0b, 0xe8, 0x9d, 0x06, 0x8c, 0x4a, 0x12, 0x61, 0x87,
	0x34, 0x62, 0xc4, 0xa0, 0x27, 0xa6, 0xd3, 0xe4, 0x74, 0x37, 0xf0, 0x29, 0x66, 0xc7, 0xbf, 0x3d,
	0x82, 0x7d, 0xf3, 0x2f, 0xc7, 0xac, 0xef, 0xa8, 0x33, 0xbd, 0xed, 0x61, 0x38, 0xe2, 0x24, 0x66,
	0xc6, 0x7d, 0xd0, 0xca, 0xa5, 0x57, 0xed, 0xb4, 0x6d, 0x98, 0x0a, 0x58, 0x62, 0x99, 0x80, 0x97,
	0x4f, 0x3c, 0x15, 0x43, 0x4e, 0x19, 0x34, 0x76, 0xc0, 0xa2, 0x7c, 0x6e, 0x66, 0xea, 0x92, 0xba,
	0x96, 0x0a, 0x98, 0x23, 0x99, 0x80, 0x17, 0x2b, 0xc6, 0x60, 0xc8, 0xc9, 0x03, 0x95, 0x8e, 0xbe,
	0xeb, 0x60, 0x75, 0xc0, 0x82, 0x67, 0x61, 0x10, 0x15, 0x7b, 0x7a, 0xe6, 0xb9, 0x99, 0x3d, 0xd7,
	0x94, 0x5a, 0x6e, 0x82, 0x6b, 0xb5, 0x52, 0x16, 0xee, 0x43, 0x9f, 0x35, 0xb0, 0x36, 0x60, 0xc1,
	0x03, 0x32, 0x22, 0x9c, 0xcc, 0x55, 0xf2, 0x5b, 0xa0, 0x39, 0x24, 0x47, 0x4a, 0xeb, 0xb6, 0xbd,
	0x92, 0x0a, 0x28, 0xcf, 0x99, 0x80, 0x4b, 0x8a, 0x32, 0x39, 0x21, 0x47, 0x82, 0xf9, 0x84, 0xd7,
	0xc1, 0xe6, 0x1f, 0x7a, 0x2f, 0x66, 0xdc, 0x7e, 0xaf, 0x83, 0xc6, 0x80, 0x05, 0xc6, 0x1b, 0x0d,
	0x5c, 0xad, 0x71, 0x16, 0x3e, 0x75, 0xe1, 0x6a, 0xe5, 0xeb, 0xde, 0x9d, 0x2d, 0xbf, 0x5c, 0xf6,
	0xb7, 0x1a, 0x30, 0x6b, 0xb5, 0xbe, 0x53, 0x77, 0x69, 0x1d, 0xa3, 0xdb, 0x9f, 0x95, 0x51, 0x34,
	0x62, 0x3f, 0x7e, 0xfe, 0xe8, 0x1f, 0x3d, 0x58, 0xfc, 0xa4, 0xbd, 0x45, 0x19, 0xda, 0xf9, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x10, 0x12, 0xa6, 0x2c, 0xb7, 0x07, 0x00, 0x00,
}
