# Low Resource VPN Configuration Example
# Optimized for devices with limited CPU and memory
---
vpn:
  enable: true

  # Network settings - optimized for lower bandwidth
  mtu: 1200                     # Lower MTU to reduce fragmentation
  virtual_ip: 10.0.0.1
  subnet: 24
  routes:
    - 10.0.0.0/24
  protocol: "/vpn/1.0.0"

  # Security settings
  unallowed_ports:
    - "25"   # SMTP
    - "587"  # Submission
    - "465"  # SMTPS

  # Worker settings - reduced for lower resource usage
  worker_idle_timeout: 180      # 3 minutes
  worker_buffer_size: 50        # Smaller buffer to save memory
  max_workers: 500              # Fewer workers to reduce CPU usage
  worker_cleanup_interval: 30   # 30 seconds

  # Stream settings - reduced for lower resource usage
  max_streams_per_peer: 5       # Fewer streams to save resources
  min_streams_per_peer: 2       # Lower minimum
  stream_idle_timeout: 180      # 3 minutes
  cleanup_interval: 30          # 30 seconds

  # Circuit breaker settings - more conservative
  circuit_breaker_failure_threshold: 3   # Fewer failures allowed
  circuit_breaker_reset_timeout: 30      # 30 seconds
  circuit_breaker_success_threshold: 1   # Only one success required

  # Stream health settings - less frequent checks
  health_check_interval: 60     # 1 minute
  health_check_timeout: 10      # 10 seconds
  max_consecutive_failures: 2   # Fewer failures allowed
  warm_interval: 120            # 2 minutes

  # Retry settings - more conservative
  retry_max_attempts: 3         # Fewer retry attempts
  retry_initial_interval: 2     # 2 seconds
  retry_max_interval: 15        # 15 seconds

  # Timeout settings - optimized for lower resource usage
  peer_connection_timeout: 20       # 20 seconds - shorter timeout to save resources
  dht_sync_timeout: 30              # 30 seconds - shorter timeout to save resources
  tun_setup_timeout: 20             # 20 seconds - shorter timeout to save resources
  peer_connection_check_interval: 200  # 200 milliseconds - less frequent checks
  shutdown_grace_period: 25         # 25 milliseconds - shorter grace period
