// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deployment/v1/query.proto

package v1

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	query "github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/utils/query"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryDeploymentsRequest is request type for the Query/Deployments RPC method
type QueryDeploymentsRequest struct {
	Filters              DeploymentFilters  `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters"`
	Pagination           *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryDeploymentsRequest) Reset()         { *m = QueryDeploymentsRequest{} }
func (m *QueryDeploymentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDeploymentsRequest) ProtoMessage()    {}
func (*QueryDeploymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df8041a5efa8ab, []int{0}
}
func (m *QueryDeploymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeploymentsRequest.Unmarshal(m, b)
}
func (m *QueryDeploymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeploymentsRequest.Marshal(b, m, deterministic)
}
func (m *QueryDeploymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeploymentsRequest.Merge(m, src)
}
func (m *QueryDeploymentsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDeploymentsRequest.Size(m)
}
func (m *QueryDeploymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeploymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeploymentsRequest proto.InternalMessageInfo

func (m *QueryDeploymentsRequest) GetFilters() DeploymentFilters {
	if m != nil {
		return m.Filters
	}
	return DeploymentFilters{}
}

func (m *QueryDeploymentsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryDeploymentsResponse is response type for the Query/Deployments RPC method
type QueryDeploymentsResponse struct {
	Deployments          DeploymentResponses `protobuf:"bytes,1,rep,name=deployments,proto3,castrepeated=DeploymentResponses" json:"deployments"`
	Pagination           *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryDeploymentsResponse) Reset()         { *m = QueryDeploymentsResponse{} }
func (m *QueryDeploymentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDeploymentsResponse) ProtoMessage()    {}
func (*QueryDeploymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df8041a5efa8ab, []int{1}
}
func (m *QueryDeploymentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeploymentsResponse.Unmarshal(m, b)
}
func (m *QueryDeploymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeploymentsResponse.Marshal(b, m, deterministic)
}
func (m *QueryDeploymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeploymentsResponse.Merge(m, src)
}
func (m *QueryDeploymentsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDeploymentsResponse.Size(m)
}
func (m *QueryDeploymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeploymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeploymentsResponse proto.InternalMessageInfo

func (m *QueryDeploymentsResponse) GetDeployments() DeploymentResponses {
	if m != nil {
		return m.Deployments
	}
	return nil
}

func (m *QueryDeploymentsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryDeploymentRequest is request type for the Query/Deployment RPC method
type QueryDeploymentRequest struct {
	ID                   DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryDeploymentRequest) Reset()         { *m = QueryDeploymentRequest{} }
func (m *QueryDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDeploymentRequest) ProtoMessage()    {}
func (*QueryDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df8041a5efa8ab, []int{2}
}
func (m *QueryDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeploymentRequest.Unmarshal(m, b)
}
func (m *QueryDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *QueryDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeploymentRequest.Merge(m, src)
}
func (m *QueryDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDeploymentRequest.Size(m)
}
func (m *QueryDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeploymentRequest proto.InternalMessageInfo

func (m *QueryDeploymentRequest) GetID() DeploymentID {
	if m != nil {
		return m.ID
	}
	return DeploymentID{}
}

// QueryDeploymentResponse is response type for the Query/Deployment RPC method
type QueryDeploymentResponse struct {
	Deployment           Deployment `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment" yaml:"deployment"`
	Groups               []Group    `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups" yaml:"groups"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryDeploymentResponse) Reset()         { *m = QueryDeploymentResponse{} }
func (m *QueryDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDeploymentResponse) ProtoMessage()    {}
func (*QueryDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df8041a5efa8ab, []int{3}
}
func (m *QueryDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeploymentResponse.Unmarshal(m, b)
}
func (m *QueryDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeploymentResponse.Marshal(b, m, deterministic)
}
func (m *QueryDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeploymentResponse.Merge(m, src)
}
func (m *QueryDeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDeploymentResponse.Size(m)
}
func (m *QueryDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeploymentResponse proto.InternalMessageInfo

func (m *QueryDeploymentResponse) GetDeployment() Deployment {
	if m != nil {
		return m.Deployment
	}
	return Deployment{}
}

func (m *QueryDeploymentResponse) GetGroups() []Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

// QueryGroupRequest is request type for the Query/Group RPC method
type QueryGroupRequest struct {
	ID                   GroupID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGroupRequest) Reset()         { *m = QueryGroupRequest{} }
func (m *QueryGroupRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGroupRequest) ProtoMessage()    {}
func (*QueryGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df8041a5efa8ab, []int{4}
}
func (m *QueryGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGroupRequest.Unmarshal(m, b)
}
func (m *QueryGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGroupRequest.Marshal(b, m, deterministic)
}
func (m *QueryGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGroupRequest.Merge(m, src)
}
func (m *QueryGroupRequest) XXX_Size() int {
	return xxx_messageInfo_QueryGroupRequest.Size(m)
}
func (m *QueryGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGroupRequest proto.InternalMessageInfo

func (m *QueryGroupRequest) GetID() GroupID {
	if m != nil {
		return m.ID
	}
	return GroupID{}
}

// QueryGroupResponse is response type for the Query/Group RPC method
type QueryGroupResponse struct {
	Group                Group    `protobuf:"bytes,1,opt,name=group,proto3" json:"group"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGroupResponse) Reset()         { *m = QueryGroupResponse{} }
func (m *QueryGroupResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGroupResponse) ProtoMessage()    {}
func (*QueryGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93df8041a5efa8ab, []int{5}
}
func (m *QueryGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGroupResponse.Unmarshal(m, b)
}
func (m *QueryGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGroupResponse.Marshal(b, m, deterministic)
}
func (m *QueryGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGroupResponse.Merge(m, src)
}
func (m *QueryGroupResponse) XXX_Size() int {
	return xxx_messageInfo_QueryGroupResponse.Size(m)
}
func (m *QueryGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGroupResponse proto.InternalMessageInfo

func (m *QueryGroupResponse) GetGroup() Group {
	if m != nil {
		return m.Group
	}
	return Group{}
}

func init() {
	proto.RegisterType((*QueryDeploymentsRequest)(nil), "subnet.k8s.deployment.v1.QueryDeploymentsRequest")
	proto.RegisterType((*QueryDeploymentsResponse)(nil), "subnet.k8s.deployment.v1.QueryDeploymentsResponse")
	proto.RegisterType((*QueryDeploymentRequest)(nil), "subnet.k8s.deployment.v1.QueryDeploymentRequest")
	proto.RegisterType((*QueryDeploymentResponse)(nil), "subnet.k8s.deployment.v1.QueryDeploymentResponse")
	proto.RegisterType((*QueryGroupRequest)(nil), "subnet.k8s.deployment.v1.QueryGroupRequest")
	proto.RegisterType((*QueryGroupResponse)(nil), "subnet.k8s.deployment.v1.QueryGroupResponse")
}

func init() { proto.RegisterFile("deployment/v1/query.proto", fileDescriptor_93df8041a5efa8ab) }

var fileDescriptor_93df8041a5efa8ab = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xdd, 0x0f, 0xa4, 0x89, 0x38, 0x74, 0x41, 0x10, 0x52, 0x84, 0xc1, 0x14, 0x5a, 0xd1,
	0xd6, 0x4b, 0xc2, 0xa5, 0x2a, 0xe2, 0x62, 0x22, 0x50, 0x05, 0x42, 0xd4, 0x27, 0x84, 0xb8, 0x38,
	0xb5, 0x63, 0x56, 0x75, 0x76, 0x5d, 0xef, 0xba, 0x52, 0xae, 0xfc, 0x03, 0xc4, 0x1f, 0xe0, 0x82,
	0x84, 0xe0, 0x8f, 0x70, 0x86, 0x7b, 0x90, 0x10, 0x87, 0x8a, 0x03, 0x87, 0xfe, 0x02, 0xe4, 0xdd,
	0x4d, 0xed, 0x36, 0x31, 0x49, 0x6e, 0x49, 0xde, 0xcc, 0x7b, 0x6f, 0xde, 0xce, 0x6e, 0xe0, 0x5a,
	0x10, 0x26, 0x31, 0xeb, 0xf7, 0x42, 0x2a, 0xf0, 0x51, 0x13, 0x1f, 0x66, 0x61, 0xda, 0x77, 0x92,
	0x94, 0x09, 0x86, 0xea, 0x3c, 0xeb, 0xd0, 0x50, 0x38, 0x07, 0xdb, 0xdc, 0x29, 0xaa, 0x9c, 0xa3,
	0x66, 0xe3, 0x72, 0xc4, 0x22, 0x26, 0x8b, 0x70, 0xfe, 0x49, 0xd5, 0x37, 0xae, 0x47, 0x8c, 0x45,
	0x71, 0x88, 0xfd, 0x84, 0x60, 0x9f, 0x52, 0x26, 0x7c, 0x41, 0x18, 0xe5, 0x43, 0x34, 0x13, 0x24,
	0xe6, 0x4a, 0x00, 0x27, 0x7e, 0x44, 0xa8, 0x84, 0x35, 0x7a, 0xe3, 0xac, 0x8d, 0x92, 0x9c, 0xc2,
	0xcf, 0xd9, 0x8c, 0x52, 0x96, 0x25, 0x1a, 0x5a, 0x19, 0x03, 0x91, 0x40, 0x81, 0xf6, 0x57, 0x03,
	0xae, 0xee, 0xe5, 0x92, 0xed, 0xd3, 0x22, 0xee, 0x85, 0x87, 0x59, 0xc8, 0x05, 0x7a, 0x06, 0x17,
	0xba, 0x24, 0x16, 0x61, 0xca, 0xeb, 0xc6, 0x4d, 0x63, 0xbd, 0xd6, 0xda, 0x70, 0xaa, 0x26, 0x76,
	0x8a, 0xf6, 0x27, 0xaa, 0xc5, 0x5d, 0xf8, 0x36, 0xb0, 0xe6, 0xbc, 0x21, 0x03, 0x7a, 0x0c, 0x50,
	0x0c, 0x55, 0x37, 0x25, 0xdf, 0xed, 0x32, 0x9f, 0x1c, 0xdf, 0x51, 0xf9, 0xbe, 0xf4, 0xa3, 0x50,
	0xbb, 0xf0, 0x4a, 0x6d, 0xf6, 0x77, 0x03, 0xea, 0xa3, 0x6e, 0x79, 0xc2, 0x28, 0x0f, 0x51, 0x02,
	0xb5, 0xc2, 0x53, 0x6e, 0x79, 0x7e, 0xbd, 0xd6, 0x6a, 0x56, 0x5b, 0x3e, 0x47, 0x34, 0xe4, 0x71,
	0x57, 0x72, 0xe3, 0x5f, 0x7e, 0x5a, 0x97, 0x46, 0x31, 0xee, 0x95, 0x25, 0x50, 0x7b, 0xcc, 0x4c,
	0xab, 0xff, 0x9f, 0x49, 0xf1, 0x9c, 0x19, 0xea, 0x0d, 0x5c, 0x19, 0xb1, 0xa2, 0x0e, 0xc0, 0x05,
	0x93, 0x04, 0x3a, 0xfb, 0xbb, 0xd3, 0x64, 0xbf, 0xdb, 0x76, 0x21, 0x77, 0xff, 0x6b, 0x60, 0x99,
	0xbb, 0x6d, 0xcf, 0x24, 0x81, 0x7d, 0x3c, 0x7a, 0xc0, 0xa7, 0x89, 0xf5, 0x00, 0x0a, 0x26, 0xad,
	0xb3, 0x3a, 0x8d, 0x8e, 0xbb, 0x96, 0xab, 0xfc, 0x19, 0x58, 0xa5, 0xfe, 0x93, 0x81, 0xb5, 0xdc,
	0xf7, 0x7b, 0xf1, 0x8e, 0x5d, 0xfc, 0x66, 0x7b, 0xa5, 0x02, 0xf4, 0x0a, 0x96, 0xe4, 0xf2, 0xf1,
	0xba, 0x29, 0xcf, 0xc6, 0xaa, 0x96, 0x7a, 0x9a, 0xd7, 0xb9, 0x96, 0x56, 0xd1, 0x6d, 0x27, 0x03,
	0xeb, 0xa2, 0x52, 0x50, 0xdf, 0x6d, 0x4f, 0x03, 0x3b, 0x0b, 0xc7, 0x1f, 0xad, 0x39, 0xdb, 0x83,
	0x65, 0x39, 0xa9, 0x6c, 0x1e, 0x66, 0xf8, 0xa8, 0x94, 0xe1, 0xad, 0x09, 0x82, 0x63, 0xe2, 0xdb,
	0x03, 0x54, 0xe6, 0xd4, 0xc1, 0x3d, 0x84, 0x45, 0xa9, 0xac, 0x79, 0x27, 0x0e, 0xa2, 0xee, 0x82,
	0xea, 0x69, 0xfd, 0x9d, 0x87, 0x45, 0xc9, 0x89, 0x3e, 0x1b, 0x50, 0x2b, 0x6d, 0x32, 0x9a, 0x7e,
	0x59, 0x87, 0x77, 0xb4, 0xd1, 0x9a, 0xa5, 0x45, 0xb9, 0xb7, 0x5b, 0xef, 0x7e, 0xfc, 0xfe, 0x60,
	0x6e, 0xa2, 0x7b, 0x58, 0xf5, 0xe2, 0x83, 0x6d, 0x8e, 0xab, 0xde, 0x17, 0x8e, 0x63, 0xc2, 0x05,
	0xfa, 0x64, 0x00, 0x14, 0x5c, 0xe8, 0xfe, 0x0c, 0xd7, 0x4a, 0x19, 0x9d, 0xfd, 0x22, 0xce, 0xea,
	0x93, 0xd0, 0x2e, 0x43, 0xef, 0x0d, 0x58, 0x94, 0x99, 0xa3, 0x8d, 0x09, 0x82, 0xe5, 0x2d, 0x69,
	0x6c, 0x4e, 0x57, 0xac, 0x8d, 0x6d, 0x49, 0x63, 0x6b, 0xe8, 0x4e, 0xb5, 0x31, 0xb5, 0x98, 0xd2,
	0x93, 0xfb, 0xe2, 0xf5, 0xf3, 0x88, 0x88, 0xb7, 0x59, 0xc7, 0xd9, 0x67, 0x3d, 0x9c, 0x51, 0xb2,
	0xcf, 0x52, 0x9a, 0xc5, 0x22, 0xf5, 0xbb, 0x2c, 0xa3, 0x81, 0x7c, 0x05, 0x34, 0xd3, 0x16, 0x65,
	0x41, 0x88, 0xd5, 0x3f, 0x47, 0x15, 0x77, 0x67, 0x49, 0xe2, 0x0f, 0xfe, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xed, 0x75, 0xac, 0x9b, 0x06, 0x00, 0x00,
}
