// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deployment/v1/resourceunit.proto

package v1

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	v1 "github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/base/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ResourceUnit extends Resources and adds Count along with the Price
type ResourceUnit struct {
	v1.Resources `protobuf:"bytes,1,opt,name=resource,proto3,embedded=resource" json:"resource" yaml:"resource"`
	Count        uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count" yaml:"count"`
}

func (m *ResourceUnit) Reset()         { *m = ResourceUnit{} }
func (m *ResourceUnit) String() string { return proto.CompactTextString(m) }
func (*ResourceUnit) ProtoMessage()    {}
func (*ResourceUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d20ef424fc28ba0a, []int{0}
}
func (m *ResourceUnit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResourceUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResourceUnit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResourceUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceUnit.Merge(m, src)
}
func (m *ResourceUnit) XXX_Size() int {
	return m.Size()
}
func (m *ResourceUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceUnit.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceUnit proto.InternalMessageInfo

func (m *ResourceUnit) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*ResourceUnit)(nil), "subnet.k8s.deployment.v1.ResourceUnit")
}

func init() { proto.RegisterFile("deployment/v1/resourceunit.proto", fileDescriptor_d20ef424fc28ba0a) }

var fileDescriptor_d20ef424fc28ba0a = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x63, 0x04, 0x08, 0x85, 0x22, 0xa4, 0x0a, 0x89, 0x52, 0x09, 0xbb, 0xca, 0x42, 0x17,
	0x6c, 0x15, 0x96, 0xaa, 0x63, 0x67, 0xa6, 0x4a, 0x2c, 0x6c, 0xf9, 0x71, 0x43, 0xd4, 0xc4, 0xb7,
	0x8a, 0xed, 0x48, 0x7d, 0x0b, 0x1e, 0x81, 0x95, 0x37, 0xe9, 0x98, 0x91, 0xc9, 0x42, 0xc9, 0x82,
	0x3a, 0xf6, 0x09, 0x50, 0x63, 0x52, 0xca, 0x66, 0x7f, 0xe7, 0x3b, 0xd7, 0xf2, 0x75, 0x07, 0x11,
	0x5f, 0xa6, 0xb0, 0xca, 0xb8, 0x50, 0xac, 0x18, 0xb1, 0x9c, 0x4b, 0xd0, 0x79, 0xc8, 0xb5, 0x48,
	0x14, 0x5d, 0xe6, 0xa0, 0xa0, 0xdb, 0x93, 0x3a, 0x10, 0x5c, 0xd1, 0xc5, 0x58, 0xd2, 0x3f, 0x99,
	0x16, 0xa3, 0xfe, 0x55, 0x0c, 0x31, 0x34, 0x12, 0xdb, 0x9d, 0xac, 0xdf, 0xbf, 0x0e, 0x7c, 0xc9,
	0x0f, 0x67, 0x49, 0x1b, 0x78, 0x1f, 0xc8, 0xed, 0xcc, 0x7e, 0xd9, 0xb3, 0x48, 0x54, 0x37, 0x70,
	0xcf, 0x5a, 0xa7, 0x87, 0x06, 0x68, 0x78, 0xfe, 0x70, 0x4b, 0x0f, 0x1e, 0xdb, 0xcd, 0xa1, 0xc5,
	0x88, 0xb6, 0x1d, 0x39, 0xbd, 0x5b, 0x1b, 0xe2, 0x94, 0x86, 0xa0, 0x8d, 0x21, 0xfb, 0xea, 0xd6,
	0x90, 0xcb, 0x95, 0x9f, 0xa5, 0x13, 0xaf, 0x25, 0xde, 0x6c, 0x1f, 0x76, 0x99, 0x7b, 0x12, 0x82,
	0x16, 0xaa, 0x77, 0x34, 0x40, 0xc3, 0x8b, 0xe9, 0xcd, 0xc6, 0x10, 0x0b, 0xb6, 0x86, 0x74, 0x6c,
	0xad, 0xb9, 0x7a, 0x33, 0x8b, 0x27, 0xc7, 0xdf, 0xef, 0x04, 0x4d, 0xe7, 0xeb, 0x0a, 0xa3, 0xb2,
	0xc2, 0xe8, 0xab, 0xc2, 0xe8, 0xad, 0xc6, 0x4e, 0x59, 0x63, 0xe7, 0xb3, 0xc6, 0xce, 0xcb, 0x53,
	0x9c, 0xa8, 0x57, 0x1d, 0xd0, 0x10, 0x32, 0xa6, 0x45, 0x12, 0x42, 0x2e, 0x74, 0xaa, 0x72, 0x7f,
	0x0e, 0x5a, 0x44, 0xbe, 0x4a, 0x40, 0x30, 0xfb, 0x87, 0x7b, 0x01, 0x11, 0x67, 0x76, 0x3d, 0x96,
	0xb0, 0xc5, 0x58, 0xb2, 0x7f, 0xfb, 0x0e, 0x4e, 0x9b, 0xfc, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xb1, 0xa5, 0x65, 0xd7, 0x87, 0x01, 0x00, 0x00,
}

func (this *ResourceUnit) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResourceUnit)
	if !ok {
		that2, ok := that.(ResourceUnit)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Resources.Equal(&that1.Resources) {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	return true
}
func (m *ResourceUnit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResourceUnit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResourceUnit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintResourceunit(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Resources.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintResourceunit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintResourceunit(dAtA []byte, offset int, v uint64) int {
	offset -= sovResourceunit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ResourceUnit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Resources.Size()
	n += 1 + l + sovResourceunit(uint64(l))
	if m.Count != 0 {
		n += 1 + sovResourceunit(uint64(m.Count))
	}
	return n
}

func sovResourceunit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResourceunit(x uint64) (n int) {
	return sovResourceunit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ResourceUnit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResourceunit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResourceUnit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResourceUnit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthResourceunit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthResourceunit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Resources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResourceunit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResourceunit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResourceunit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResourceunit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourceunit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResourceunit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResourceunit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResourceunit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResourceunit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResourceunit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResourceunit = fmt.Errorf("proto: unexpected end of group")
)
