// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: utils/query/pagination.proto

package query

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PageRequest is to be embedded in gRPC request messages for efficient
// pagination. Ex:
//
//	message SomeRequest {
//	        Foo some_parameter = 1;
//	        PageRequest pagination = 2;
//	}
type PageRequest struct {
	// key is a value returned in PageResponse.next_key to begin
	// querying the next page most efficiently. Only one of offset or key
	// should be set.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// offset is a numeric offset that can be used when key is unavailable.
	// It is less efficient than using key. Only one of offset or key should
	// be set.
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit is the total number of results to be returned in the result page.
	// If left empty it will default to a value to be set by each app.
	Limit uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// count_total is set to true  to indicate that the result set should include
	// a count of the total number of items available for pagination in UIs.
	// count_total is only respected when offset is used. It is ignored when key
	// is set.
	CountTotal bool `protobuf:"varint,4,opt,name=count_total,json=countTotal,proto3" json:"count_total,omitempty"`
	// reverse is set to true if results are to be returned in the descending order.
	//
	// Since: cosmos-sdk 0.43
	Reverse              bool     `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bce5eb5b02968379, []int{0}
}
func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PageRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PageRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PageRequest) GetCountTotal() bool {
	if m != nil {
		return m.CountTotal
	}
	return false
}

func (m *PageRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

// PageResponse is to be embedded in gRPC response messages where the
// corresponding request message has used PageRequest.
//
//	message SomeResponse {
//	        repeated Bar results = 1;
//	        PageResponse page = 2;
//	}
type PageResponse struct {
	// next_key is the key to be passed to PageRequest.key to
	// query the next page most efficiently
	NextKey []byte `protobuf:"bytes,1,opt,name=next_key,json=nextKey,proto3" json:"next_key,omitempty"`
	// total is total number of results available if PageRequest.count_total
	// was set, its value is undefined otherwise
	Total                uint64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageResponse) Reset()         { *m = PageResponse{} }
func (m *PageResponse) String() string { return proto.CompactTextString(m) }
func (*PageResponse) ProtoMessage()    {}
func (*PageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bce5eb5b02968379, []int{1}
}
func (m *PageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResponse.Unmarshal(m, b)
}
func (m *PageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResponse.Marshal(b, m, deterministic)
}
func (m *PageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResponse.Merge(m, src)
}
func (m *PageResponse) XXX_Size() int {
	return xxx_messageInfo_PageResponse.Size(m)
}
func (m *PageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PageResponse proto.InternalMessageInfo

func (m *PageResponse) GetNextKey() []byte {
	if m != nil {
		return m.NextKey
	}
	return nil
}

func (m *PageResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*PageRequest)(nil), "subnet.k8s.utils.query.PageRequest")
	proto.RegisterType((*PageResponse)(nil), "subnet.k8s.utils.query.PageResponse")
}

func init() { proto.RegisterFile("utils/query/pagination.proto", fileDescriptor_bce5eb5b02968379) }

var fileDescriptor_bce5eb5b02968379 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0xfb, 0x49, 0x76, 0x0f, 0x12, 0x64, 0x89, 0x20, 0x58, 0xf6, 0xd4, 0x8b, 0xcd,
	0xc1, 0xcb, 0xde, 0x04, 0x8f, 0xea, 0x41, 0x8a, 0x27, 0x2f, 0x4b, 0xda, 0x9d, 0xd6, 0xd0, 0x6e,
	0xa6, 0x9b, 0x4c, 0xc4, 0xfe, 0x03, 0x7f, 0xb6, 0x34, 0x59, 0xd1, 0x5b, 0x9e, 0x77, 0x86, 0xcc,
	0xcb, 0xc3, 0x6e, 0x3c, 0xe9, 0xce, 0xc9, 0x93, 0x07, 0x3b, 0xc8, 0x5e, 0x35, 0xda, 0x28, 0xd2,
	0x68, 0xf2, 0xde, 0x22, 0x21, 0xdf, 0x38, 0x5f, 0x1a, 0xa0, 0xbc, 0xdd, 0xb9, 0x3c, 0x2c, 0xe6,
	0x61, 0x71, 0xfb, 0x9d, 0xb0, 0xd5, 0xab, 0x6a, 0xa0, 0x80, 0x93, 0x07, 0x47, 0xfc, 0x92, 0x4d,
	0x5a, 0x18, 0x44, 0x92, 0x26, 0xd9, 0xba, 0x18, 0x9f, 0x7c, 0xc3, 0xe6, 0x58, 0xd7, 0x0e, 0x48,
	0x5c, 0xa4, 0x49, 0x36, 0x2d, 0xce, 0xc4, 0xaf, 0xd8, 0xac, 0xd3, 0x47, 0x4d, 0x62, 0x12, 0xe2,
	0x08, 0xfc, 0x96, 0xad, 0x2a, 0xf4, 0x86, 0xf6, 0x84, 0xa4, 0x3a, 0x31, 0x4d, 0x93, 0x6c, 0x59,
	0xb0, 0x10, 0xbd, 0x8d, 0x09, 0x17, 0x6c, 0x61, 0xe1, 0x13, 0xac, 0x03, 0x31, 0x0b, 0xc3, 0x5f,
	0xdc, 0x3e, 0xb0, 0x75, 0x6c, 0xe2, 0x7a, 0x34, 0x0e, 0xf8, 0x35, 0x5b, 0x1a, 0xf8, 0xa2, 0xfd,
	0x5f, 0x9f, 0xc5, 0xc8, 0xcf, 0x30, 0x8c, 0xb7, 0xe3, 0xff, 0xb1, 0x52, 0x84, 0xc7, 0x97, 0xf7,
	0xa7, 0x46, 0xd3, 0x87, 0x2f, 0xf3, 0x0a, 0x8f, 0xd2, 0x1b, 0x5d, 0xa1, 0x35, 0xbe, 0x23, 0xab,
	0x6a, 0xf4, 0xe6, 0x10, 0x74, 0xc8, 0xe8, 0xe1, 0xce, 0xe0, 0x01, 0x64, 0x50, 0x73, 0x4e, 0x64,
	0xbb, 0x73, 0xf2, 0x9f, 0xc2, 0x72, 0x1e, 0xa6, 0xf7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd,
	0x14, 0x94, 0x7a, 0x58, 0x01, 0x00, 0x00,
}
