// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: provider/v1/service.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderRPC_GetStatus_FullMethodName    = "/subnet.k8s.provider.v1.ProviderRPC/GetStatus"
	ProviderRPC_StreamStatus_FullMethodName = "/subnet.k8s.provider.v1.ProviderRPC/StreamStatus"
)

// ProviderRPCClient is the client API for ProviderRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProviderRPC defines the RPC server for provider
type ProviderRPCClient interface {
	// GetStatus defines a method to query provider state
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error)
	// Status defines a method to stream provider state
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Status], error)
}

type providerRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderRPCClient(cc grpc.ClientConnInterface) ProviderRPCClient {
	return &providerRPCClient{cc}
}

func (c *providerRPCClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, ProviderRPC_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerRPCClient) StreamStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Status], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderRPC_ServiceDesc.Streams[0], ProviderRPC_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Status]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderRPC_StreamStatusClient = grpc.ServerStreamingClient[Status]

// ProviderRPCServer is the server API for ProviderRPC service.
// All implementations must embed UnimplementedProviderRPCServer
// for forward compatibility.
//
// ProviderRPC defines the RPC server for provider
type ProviderRPCServer interface {
	// GetStatus defines a method to query provider state
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetStatus(context.Context, *emptypb.Empty) (*Status, error)
	// Status defines a method to stream provider state
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamStatus(*emptypb.Empty, grpc.ServerStreamingServer[Status]) error
	mustEmbedUnimplementedProviderRPCServer()
}

// UnimplementedProviderRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderRPCServer struct{}

func (UnimplementedProviderRPCServer) GetStatus(context.Context, *emptypb.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedProviderRPCServer) StreamStatus(*emptypb.Empty, grpc.ServerStreamingServer[Status]) error {
	return status.Errorf(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedProviderRPCServer) mustEmbedUnimplementedProviderRPCServer() {}
func (UnimplementedProviderRPCServer) testEmbeddedByValue()                     {}

// UnsafeProviderRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderRPCServer will
// result in compilation errors.
type UnsafeProviderRPCServer interface {
	mustEmbedUnimplementedProviderRPCServer()
}

func RegisterProviderRPCServer(s grpc.ServiceRegistrar, srv ProviderRPCServer) {
	// If the following call pancis, it indicates UnimplementedProviderRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderRPC_ServiceDesc, srv)
}

func _ProviderRPC_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderRPCServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderRPC_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderRPCServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderRPC_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderRPCServer).StreamStatus(m, &grpc.GenericServerStream[emptypb.Empty, Status]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderRPC_StreamStatusServer = grpc.ServerStreamingServer[Status]

// ProviderRPC_ServiceDesc is the grpc.ServiceDesc for ProviderRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subnet.k8s.provider.v1.ProviderRPC",
	HandlerType: (*ProviderRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ProviderRPC_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _ProviderRPC_StreamStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider/v1/service.proto",
}
