// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: market/v1/lease.proto

package v1

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// State is an enum which refers to state of lease
type Lease_State int32

const (
	// Prefix should start with 0 in enum. So declaring dummy state
	LeaseStateInvalid Lease_State = 0
	// LeaseActive denotes state for lease active
	LeaseActive Lease_State = 1
	// LeaseInsufficientFunds denotes state for lease insufficient_funds
	LeaseInsufficientFunds Lease_State = 2
	// LeaseClosed denotes state for lease closed
	LeaseClosed Lease_State = 3
)

var Lease_State_name = map[int32]string{
	0: "invalid",
	1: "active",
	2: "insufficient_funds",
	3: "closed",
}

var Lease_State_value = map[string]int32{
	"invalid":            0,
	"active":             1,
	"insufficient_funds": 2,
	"closed":             3,
}

func (x Lease_State) String() string {
	return proto.EnumName(Lease_State_name, int32(x))
}

func (Lease_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{1, 0}
}

// LeaseID stores bid details of lease
type LeaseID struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	DSeq                 uint64   `protobuf:"varint,2,opt,name=dseq,proto3" json:"dseq" yaml:"dseq"`
	GSeq                 uint32   `protobuf:"varint,3,opt,name=gseq,proto3" json:"gseq" yaml:"gseq"`
	OSeq                 uint32   `protobuf:"varint,4,opt,name=oseq,proto3" json:"oseq" yaml:"oseq"`
	Provider             string   `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider" yaml:"provider"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseID) Reset()      { *m = LeaseID{} }
func (*LeaseID) ProtoMessage() {}
func (*LeaseID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{0}
}
func (m *LeaseID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseID.Unmarshal(m, b)
}
func (m *LeaseID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseID.Marshal(b, m, deterministic)
}
func (m *LeaseID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseID.Merge(m, src)
}
func (m *LeaseID) XXX_Size() int {
	return xxx_messageInfo_LeaseID.Size(m)
}
func (m *LeaseID) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseID.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseID proto.InternalMessageInfo

func (m *LeaseID) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *LeaseID) GetDSeq() uint64 {
	if m != nil {
		return m.DSeq
	}
	return 0
}

func (m *LeaseID) GetGSeq() uint32 {
	if m != nil {
		return m.GSeq
	}
	return 0
}

func (m *LeaseID) GetOSeq() uint32 {
	if m != nil {
		return m.OSeq
	}
	return 0
}

func (m *LeaseID) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

// Lease stores LeaseID, state of lease and price
type Lease struct {
	LeaseID              LeaseID     `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"id" yaml:"id"`
	State                Lease_State `protobuf:"varint,2,opt,name=state,proto3,enum=subnet.k8s.market.v1.Lease_State" json:"state" yaml:"state"`
	CreatedAt            int64       `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedOn             int64       `protobuf:"varint,4,opt,name=closed_on,json=closedOn,proto3" json:"closed_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Lease) Reset()      { *m = Lease{} }
func (*Lease) ProtoMessage() {}
func (*Lease) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{1}
}
func (m *Lease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lease.Unmarshal(m, b)
}
func (m *Lease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lease.Marshal(b, m, deterministic)
}
func (m *Lease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lease.Merge(m, src)
}
func (m *Lease) XXX_Size() int {
	return xxx_messageInfo_Lease.Size(m)
}
func (m *Lease) XXX_DiscardUnknown() {
	xxx_messageInfo_Lease.DiscardUnknown(m)
}

var xxx_messageInfo_Lease proto.InternalMessageInfo

func (m *Lease) GetLeaseID() LeaseID {
	if m != nil {
		return m.LeaseID
	}
	return LeaseID{}
}

func (m *Lease) GetState() Lease_State {
	if m != nil {
		return m.State
	}
	return LeaseStateInvalid
}

func (m *Lease) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Lease) GetClosedOn() int64 {
	if m != nil {
		return m.ClosedOn
	}
	return 0
}

// LeaseFilters defines flags for lease list filter
type LeaseFilters struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	DSeq                 uint64   `protobuf:"varint,2,opt,name=dseq,proto3" json:"dseq" yaml:"dseq"`
	GSeq                 uint32   `protobuf:"varint,3,opt,name=gseq,proto3" json:"gseq" yaml:"gseq"`
	OSeq                 uint32   `protobuf:"varint,4,opt,name=oseq,proto3" json:"oseq" yaml:"oseq"`
	Provider             string   `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider" yaml:"provider"`
	State                string   `protobuf:"bytes,6,opt,name=state,proto3" json:"state" yaml:"state"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseFilters) Reset()         { *m = LeaseFilters{} }
func (m *LeaseFilters) String() string { return proto.CompactTextString(m) }
func (*LeaseFilters) ProtoMessage()    {}
func (*LeaseFilters) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{2}
}
func (m *LeaseFilters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseFilters.Unmarshal(m, b)
}
func (m *LeaseFilters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseFilters.Marshal(b, m, deterministic)
}
func (m *LeaseFilters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseFilters.Merge(m, src)
}
func (m *LeaseFilters) XXX_Size() int {
	return xxx_messageInfo_LeaseFilters.Size(m)
}
func (m *LeaseFilters) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseFilters.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseFilters proto.InternalMessageInfo

func (m *LeaseFilters) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *LeaseFilters) GetDSeq() uint64 {
	if m != nil {
		return m.DSeq
	}
	return 0
}

func (m *LeaseFilters) GetGSeq() uint32 {
	if m != nil {
		return m.GSeq
	}
	return 0
}

func (m *LeaseFilters) GetOSeq() uint32 {
	if m != nil {
		return m.OSeq
	}
	return 0
}

func (m *LeaseFilters) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *LeaseFilters) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

// MsgCreateLease is sent to create a lease
type MsgCreateLease struct {
	BidID                BidID    `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"id" yaml:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateLease) Reset()         { *m = MsgCreateLease{} }
func (m *MsgCreateLease) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLease) ProtoMessage()    {}
func (*MsgCreateLease) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{3}
}
func (m *MsgCreateLease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateLease.Unmarshal(m, b)
}
func (m *MsgCreateLease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateLease.Marshal(b, m, deterministic)
}
func (m *MsgCreateLease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLease.Merge(m, src)
}
func (m *MsgCreateLease) XXX_Size() int {
	return xxx_messageInfo_MsgCreateLease.Size(m)
}
func (m *MsgCreateLease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLease proto.InternalMessageInfo

func (m *MsgCreateLease) GetBidID() BidID {
	if m != nil {
		return m.BidID
	}
	return BidID{}
}

// MsgCreateLeaseResponse is the response from creating a lease
type MsgCreateLeaseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateLeaseResponse) Reset()         { *m = MsgCreateLeaseResponse{} }
func (m *MsgCreateLeaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLeaseResponse) ProtoMessage()    {}
func (*MsgCreateLeaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{4}
}
func (m *MsgCreateLeaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateLeaseResponse.Unmarshal(m, b)
}
func (m *MsgCreateLeaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateLeaseResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateLeaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLeaseResponse.Merge(m, src)
}
func (m *MsgCreateLeaseResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateLeaseResponse.Size(m)
}
func (m *MsgCreateLeaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLeaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLeaseResponse proto.InternalMessageInfo

// MsgWithdrawLease defines an SDK message for closing bid
type MsgWithdrawLease struct {
	LeaseID              LeaseID  `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"id" yaml:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgWithdrawLease) Reset()         { *m = MsgWithdrawLease{} }
func (m *MsgWithdrawLease) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawLease) ProtoMessage()    {}
func (*MsgWithdrawLease) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{5}
}
func (m *MsgWithdrawLease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWithdrawLease.Unmarshal(m, b)
}
func (m *MsgWithdrawLease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWithdrawLease.Marshal(b, m, deterministic)
}
func (m *MsgWithdrawLease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawLease.Merge(m, src)
}
func (m *MsgWithdrawLease) XXX_Size() int {
	return xxx_messageInfo_MsgWithdrawLease.Size(m)
}
func (m *MsgWithdrawLease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawLease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawLease proto.InternalMessageInfo

func (m *MsgWithdrawLease) GetLeaseID() LeaseID {
	if m != nil {
		return m.LeaseID
	}
	return LeaseID{}
}

// MsgWithdrawLeaseResponse defines the Msg/WithdrawLease response type.
type MsgWithdrawLeaseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgWithdrawLeaseResponse) Reset()         { *m = MsgWithdrawLeaseResponse{} }
func (m *MsgWithdrawLeaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawLeaseResponse) ProtoMessage()    {}
func (*MsgWithdrawLeaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{6}
}
func (m *MsgWithdrawLeaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWithdrawLeaseResponse.Unmarshal(m, b)
}
func (m *MsgWithdrawLeaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWithdrawLeaseResponse.Marshal(b, m, deterministic)
}
func (m *MsgWithdrawLeaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawLeaseResponse.Merge(m, src)
}
func (m *MsgWithdrawLeaseResponse) XXX_Size() int {
	return xxx_messageInfo_MsgWithdrawLeaseResponse.Size(m)
}
func (m *MsgWithdrawLeaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawLeaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawLeaseResponse proto.InternalMessageInfo

// MsgCloseLease defines an SDK message for closing order
type MsgCloseLease struct {
	LeaseID              LeaseID  `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"id" yaml:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCloseLease) Reset()         { *m = MsgCloseLease{} }
func (m *MsgCloseLease) String() string { return proto.CompactTextString(m) }
func (*MsgCloseLease) ProtoMessage()    {}
func (*MsgCloseLease) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{7}
}
func (m *MsgCloseLease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCloseLease.Unmarshal(m, b)
}
func (m *MsgCloseLease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCloseLease.Marshal(b, m, deterministic)
}
func (m *MsgCloseLease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseLease.Merge(m, src)
}
func (m *MsgCloseLease) XXX_Size() int {
	return xxx_messageInfo_MsgCloseLease.Size(m)
}
func (m *MsgCloseLease) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseLease.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseLease proto.InternalMessageInfo

func (m *MsgCloseLease) GetLeaseID() LeaseID {
	if m != nil {
		return m.LeaseID
	}
	return LeaseID{}
}

// MsgCloseLeaseResponse defines the Msg/CloseLease response type.
type MsgCloseLeaseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCloseLeaseResponse) Reset()         { *m = MsgCloseLeaseResponse{} }
func (m *MsgCloseLeaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCloseLeaseResponse) ProtoMessage()    {}
func (*MsgCloseLeaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be04d3a3720c30d, []int{8}
}
func (m *MsgCloseLeaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCloseLeaseResponse.Unmarshal(m, b)
}
func (m *MsgCloseLeaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCloseLeaseResponse.Marshal(b, m, deterministic)
}
func (m *MsgCloseLeaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseLeaseResponse.Merge(m, src)
}
func (m *MsgCloseLeaseResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCloseLeaseResponse.Size(m)
}
func (m *MsgCloseLeaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseLeaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseLeaseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("subnet.k8s.market.v1.Lease_State", Lease_State_name, Lease_State_value)
	proto.RegisterType((*LeaseID)(nil), "subnet.k8s.market.v1.LeaseID")
	proto.RegisterType((*Lease)(nil), "subnet.k8s.market.v1.Lease")
	proto.RegisterType((*LeaseFilters)(nil), "subnet.k8s.market.v1.LeaseFilters")
	proto.RegisterType((*MsgCreateLease)(nil), "subnet.k8s.market.v1.MsgCreateLease")
	proto.RegisterType((*MsgCreateLeaseResponse)(nil), "subnet.k8s.market.v1.MsgCreateLeaseResponse")
	proto.RegisterType((*MsgWithdrawLease)(nil), "subnet.k8s.market.v1.MsgWithdrawLease")
	proto.RegisterType((*MsgWithdrawLeaseResponse)(nil), "subnet.k8s.market.v1.MsgWithdrawLeaseResponse")
	proto.RegisterType((*MsgCloseLease)(nil), "subnet.k8s.market.v1.MsgCloseLease")
	proto.RegisterType((*MsgCloseLeaseResponse)(nil), "subnet.k8s.market.v1.MsgCloseLeaseResponse")
}

func init() { proto.RegisterFile("market/v1/lease.proto", fileDescriptor_8be04d3a3720c30d) }

var fileDescriptor_8be04d3a3720c30d = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xcb, 0x4e, 0xdb, 0x40,
	0x14, 0xcd, 0xcb, 0x21, 0x19, 0x5e, 0xa9, 0x0b, 0x34, 0x35, 0xa2, 0xe3, 0x7a, 0xc5, 0xa6, 0xb6,
	0x80, 0x0d, 0xa2, 0x2b, 0x02, 0xa2, 0x4d, 0x55, 0x84, 0x64, 0x2a, 0xb5, 0xaa, 0x2a, 0x45, 0x4e,
	0x66, 0x62, 0x46, 0x98, 0x19, 0xf0, 0x8c, 0x83, 0xfa, 0x07, 0x15, 0x5f, 0xd0, 0x0d, 0x2a, 0x55,
	0x7f, 0xa6, 0xeb, 0x7e, 0x80, 0x17, 0xac, 0xaa, 0x2c, 0xf3, 0x05, 0xd5, 0xcc, 0x98, 0x3c, 0x50,
	0xc4, 0xaa, 0xea, 0xaa, 0xab, 0x64, 0xce, 0xbd, 0xe7, 0xde, 0x93, 0x33, 0xc7, 0x31, 0x58, 0x3e,
	0x0b, 0xe2, 0x53, 0x2c, 0xbc, 0xde, 0x86, 0x17, 0xe1, 0x80, 0x63, 0xf7, 0x3c, 0x66, 0x82, 0x99,
	0x4b, 0x3c, 0x69, 0x53, 0x2c, 0xdc, 0xd3, 0x6d, 0xee, 0xea, 0x0e, 0xb7, 0xb7, 0x61, 0x2d, 0x85,
	0x2c, 0x64, 0xaa, 0xc1, 0x93, 0xdf, 0x74, 0xaf, 0xf5, 0x78, 0x34, 0xa2, 0x4d, 0x90, 0x06, 0x9d,
	0x9b, 0x02, 0x98, 0x79, 0x2b, 0x07, 0x36, 0xf7, 0x4d, 0x0f, 0x18, 0xec, 0x92, 0xe2, 0xb8, 0x9e,
	0xb7, 0xf3, 0xeb, 0xd5, 0xc6, 0xd3, 0x7e, 0x0a, 0x35, 0x30, 0x48, 0xe1, 0xdc, 0xe7, 0xe0, 0x2c,
	0xda, 0x71, 0xd4, 0xd1, 0xf1, 0x35, 0x6c, 0x6e, 0x81, 0x12, 0xe2, 0xf8, 0xa2, 0x5e, 0xb0, 0xf3,
	0xeb, 0xa5, 0x06, 0xbc, 0x4d, 0x61, 0x69, 0xff, 0x18, 0x5f, 0xf4, 0x53, 0xa8, 0xf0, 0x41, 0x0a,
	0x67, 0x35, 0x4d, 0x9e, 0x1c, 0x5f, 0x81, 0x92, 0x14, 0x4a, 0x52, 0xd1, 0xce, 0xaf, 0xcf, 0x6b,
	0xd2, 0xab, 0x8c, 0x14, 0x4e, 0x90, 0x42, 0x4d, 0x0a, 0x33, 0x12, 0x93, 0xa4, 0xd2, 0x88, 0x74,
	0x94, 0x91, 0xd8, 0x04, 0x89, 0x69, 0x92, 0xfc, 0x30, 0x5f, 0x82, 0xca, 0x79, 0xcc, 0x7a, 0x04,
	0xe1, 0xb8, 0x6e, 0xa8, 0x9f, 0x04, 0xfb, 0x29, 0x1c, 0x62, 0x83, 0x14, 0x2e, 0x6a, 0xd2, 0x1d,
	0xe2, 0xf8, 0xc3, 0xe2, 0x4e, 0xe5, 0xeb, 0x0d, 0xcc, 0xfd, 0xbe, 0x81, 0x39, 0xe7, 0x7b, 0x11,
	0x18, 0xca, 0x22, 0xf3, 0x13, 0xa8, 0x28, 0xf3, 0x5b, 0x04, 0x29, 0x8f, 0x66, 0x37, 0xd7, 0xdc,
	0x69, 0x17, 0xe0, 0x66, 0x8e, 0x36, 0x9c, 0x9f, 0x29, 0xcc, 0xdd, 0xa6, 0xf0, 0xce, 0xe2, 0x7e,
	0x0a, 0x0b, 0x04, 0x0d, 0x52, 0x58, 0xd5, 0x8b, 0x09, 0x72, 0xfc, 0x19, 0x35, 0xb2, 0x89, 0x4c,
	0x1f, 0x18, 0x5c, 0x04, 0x02, 0x2b, 0x3b, 0x17, 0x36, 0x9f, 0x3f, 0x30, 0xda, 0x3d, 0x96, 0x8d,
	0xfa, 0x86, 0x14, 0x67, 0x74, 0x43, 0xea, 0xe8, 0xf8, 0x1a, 0x36, 0xd7, 0x00, 0xe8, 0xc4, 0x38,
	0x10, 0x18, 0xb5, 0x02, 0xa1, 0x2c, 0x2f, 0xfa, 0xd5, 0x0c, 0xd9, 0x15, 0xe6, 0x2a, 0xa8, 0x76,
	0x22, 0xc6, 0x31, 0x6a, 0x31, 0xaa, 0xbc, 0x2d, 0xfa, 0x15, 0x0d, 0x1c, 0x51, 0xe7, 0x5b, 0x1e,
	0x18, 0x6a, 0x8f, 0xe9, 0x80, 0x19, 0x42, 0x7b, 0x41, 0x44, 0x50, 0x2d, 0x67, 0x2d, 0x5f, 0x5d,
	0xdb, 0x8f, 0x94, 0x0a, 0x55, 0x6c, 0xea, 0x82, 0xb9, 0x0a, 0xca, 0x41, 0x47, 0x90, 0x1e, 0xae,
	0xe5, 0xad, 0xc5, 0xab, 0x6b, 0x7b, 0x56, 0xb5, 0xec, 0x2a, 0xc8, 0xdc, 0x04, 0x26, 0xa1, 0x3c,
	0xe9, 0x76, 0x49, 0x87, 0x60, 0x2a, 0x5a, 0xdd, 0x84, 0x22, 0x5e, 0x2b, 0x58, 0xd6, 0xd5, 0xb5,
	0xbd, 0xa2, 0xbd, 0x19, 0x2b, 0x1f, 0xc8, 0xaa, 0x1c, 0xa8, 0xa5, 0xd4, 0x8a, 0x63, 0x03, 0xf7,
	0x14, 0x64, 0x95, 0xbe, 0xfc, 0x78, 0x96, 0x1b, 0xbb, 0xa3, 0x5f, 0x05, 0x30, 0xa7, 0xea, 0x07,
	0x24, 0x12, 0x38, 0xe6, 0xff, 0xb3, 0x3c, 0x96, 0x65, 0x69, 0x86, 0x4e, 0x56, 0x79, 0x64, 0xc6,
	0x43, 0xb1, 0xd9, 0x29, 0x29, 0x53, 0x23, 0xb0, 0x70, 0xc8, 0xc3, 0x3d, 0x95, 0x16, 0xfd, 0x00,
	0xbc, 0x03, 0xe5, 0x36, 0x41, 0xa3, 0xf8, 0xaf, 0x4e, 0xcf, 0x68, 0x83, 0xa0, 0xe6, 0x7e, 0xc3,
	0xce, 0xc2, 0x6f, 0xa8, 0xe3, 0xb4, 0xe8, 0x1b, 0x6d, 0x82, 0x9a, 0x28, 0xdb, 0x56, 0x07, 0x2b,
	0x93, 0xdb, 0x7c, 0xcc, 0xcf, 0x19, 0xe5, 0xd8, 0x89, 0x41, 0xed, 0x90, 0x87, 0xef, 0x89, 0x38,
	0x41, 0x71, 0x70, 0xa9, 0x95, 0x7c, 0xb8, 0xa7, 0xe4, 0x2f, 0x3c, 0x88, 0x13, 0x6a, 0x2c, 0x50,
	0xbf, 0xbf, 0x73, 0xa8, 0x87, 0x83, 0x79, 0xa9, 0x54, 0x26, 0xf1, 0x1f, 0xfc, 0x2f, 0x64, 0x82,
	0x9e, 0x80, 0xe5, 0x89, 0xa5, 0x77, 0x6a, 0x1a, 0x6f, 0x3e, 0xbe, 0x0e, 0x89, 0x38, 0x49, 0xda,
	0x6e, 0x87, 0x9d, 0x79, 0x09, 0x25, 0x1d, 0x16, 0xd3, 0x24, 0x12, 0x71, 0xd0, 0x65, 0x09, 0x45,
	0x81, 0x20, 0x8c, 0x7a, 0x5a, 0xcd, 0x0b, 0xca, 0x10, 0xf6, 0xf4, 0x8b, 0x41, 0x23, 0xde, 0xe9,
	0x36, 0xf7, 0x86, 0xef, 0x85, 0x76, 0x59, 0xd5, 0xb6, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0x27, 0x98, 0x34, 0x6e, 0x06, 0x00, 0x00,
}
