// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: market/v1/query.proto

package v1

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	query "github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/utils/query"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryOrdersRequest is request type for the Query/Orders RPC method
type QueryOrdersRequest struct {
	Filters              OrderFilters       `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters"`
	Pagination           *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryOrdersRequest) Reset()         { *m = QueryOrdersRequest{} }
func (m *QueryOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOrdersRequest) ProtoMessage()    {}
func (*QueryOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{0}
}
func (m *QueryOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrdersRequest.Unmarshal(m, b)
}
func (m *QueryOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrdersRequest.Marshal(b, m, deterministic)
}
func (m *QueryOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrdersRequest.Merge(m, src)
}
func (m *QueryOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOrdersRequest.Size(m)
}
func (m *QueryOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrdersRequest proto.InternalMessageInfo

func (m *QueryOrdersRequest) GetFilters() OrderFilters {
	if m != nil {
		return m.Filters
	}
	return OrderFilters{}
}

func (m *QueryOrdersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryOrdersResponse is response type for the Query/Orders RPC method
type QueryOrdersResponse struct {
	Orders               Orders              `protobuf:"bytes,1,rep,name=orders,proto3,castrepeated=Orders" json:"orders"`
	Pagination           *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryOrdersResponse) Reset()         { *m = QueryOrdersResponse{} }
func (m *QueryOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOrdersResponse) ProtoMessage()    {}
func (*QueryOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{1}
}
func (m *QueryOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrdersResponse.Unmarshal(m, b)
}
func (m *QueryOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrdersResponse.Marshal(b, m, deterministic)
}
func (m *QueryOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrdersResponse.Merge(m, src)
}
func (m *QueryOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_QueryOrdersResponse.Size(m)
}
func (m *QueryOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrdersResponse proto.InternalMessageInfo

func (m *QueryOrdersResponse) GetOrders() Orders {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *QueryOrdersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryOrderRequest is request type for the Query/Order RPC method
type QueryOrderRequest struct {
	ID                   OrderID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderRequest) Reset()         { *m = QueryOrderRequest{} }
func (m *QueryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOrderRequest) ProtoMessage()    {}
func (*QueryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{2}
}
func (m *QueryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderRequest.Unmarshal(m, b)
}
func (m *QueryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderRequest.Marshal(b, m, deterministic)
}
func (m *QueryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderRequest.Merge(m, src)
}
func (m *QueryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOrderRequest.Size(m)
}
func (m *QueryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderRequest proto.InternalMessageInfo

func (m *QueryOrderRequest) GetID() OrderID {
	if m != nil {
		return m.ID
	}
	return OrderID{}
}

// QueryOrderResponse is response type for the Query/Order RPC method
type QueryOrderResponse struct {
	Order                Order    `protobuf:"bytes,1,opt,name=order,proto3" json:"order"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderResponse) Reset()         { *m = QueryOrderResponse{} }
func (m *QueryOrderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOrderResponse) ProtoMessage()    {}
func (*QueryOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{3}
}
func (m *QueryOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderResponse.Unmarshal(m, b)
}
func (m *QueryOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderResponse.Marshal(b, m, deterministic)
}
func (m *QueryOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderResponse.Merge(m, src)
}
func (m *QueryOrderResponse) XXX_Size() int {
	return xxx_messageInfo_QueryOrderResponse.Size(m)
}
func (m *QueryOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderResponse proto.InternalMessageInfo

func (m *QueryOrderResponse) GetOrder() Order {
	if m != nil {
		return m.Order
	}
	return Order{}
}

// QueryBidsRequest is request type for the Query/Bids RPC method
type QueryBidsRequest struct {
	Filters              BidFilters         `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters"`
	Pagination           *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryBidsRequest) Reset()         { *m = QueryBidsRequest{} }
func (m *QueryBidsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBidsRequest) ProtoMessage()    {}
func (*QueryBidsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{4}
}
func (m *QueryBidsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBidsRequest.Unmarshal(m, b)
}
func (m *QueryBidsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBidsRequest.Marshal(b, m, deterministic)
}
func (m *QueryBidsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBidsRequest.Merge(m, src)
}
func (m *QueryBidsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBidsRequest.Size(m)
}
func (m *QueryBidsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBidsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBidsRequest proto.InternalMessageInfo

func (m *QueryBidsRequest) GetFilters() BidFilters {
	if m != nil {
		return m.Filters
	}
	return BidFilters{}
}

func (m *QueryBidsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryBidsResponse is response type for the Query/Bids RPC method
type QueryBidsResponse struct {
	Bids                 []QueryBidResponse  `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids"`
	Pagination           *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryBidsResponse) Reset()         { *m = QueryBidsResponse{} }
func (m *QueryBidsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBidsResponse) ProtoMessage()    {}
func (*QueryBidsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{5}
}
func (m *QueryBidsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBidsResponse.Unmarshal(m, b)
}
func (m *QueryBidsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBidsResponse.Marshal(b, m, deterministic)
}
func (m *QueryBidsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBidsResponse.Merge(m, src)
}
func (m *QueryBidsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBidsResponse.Size(m)
}
func (m *QueryBidsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBidsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBidsResponse proto.InternalMessageInfo

func (m *QueryBidsResponse) GetBids() []QueryBidResponse {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *QueryBidsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryBidRequest is request type for the Query/Bid RPC method
type QueryBidRequest struct {
	ID                   BidID    `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBidRequest) Reset()         { *m = QueryBidRequest{} }
func (m *QueryBidRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBidRequest) ProtoMessage()    {}
func (*QueryBidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{6}
}
func (m *QueryBidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBidRequest.Unmarshal(m, b)
}
func (m *QueryBidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBidRequest.Marshal(b, m, deterministic)
}
func (m *QueryBidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBidRequest.Merge(m, src)
}
func (m *QueryBidRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBidRequest.Size(m)
}
func (m *QueryBidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBidRequest proto.InternalMessageInfo

func (m *QueryBidRequest) GetID() BidID {
	if m != nil {
		return m.ID
	}
	return BidID{}
}

// QueryBidResponse is response type for the Query/Bid RPC method
type QueryBidResponse struct {
	Bid                  Bid      `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBidResponse) Reset()         { *m = QueryBidResponse{} }
func (m *QueryBidResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBidResponse) ProtoMessage()    {}
func (*QueryBidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{7}
}
func (m *QueryBidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBidResponse.Unmarshal(m, b)
}
func (m *QueryBidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBidResponse.Marshal(b, m, deterministic)
}
func (m *QueryBidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBidResponse.Merge(m, src)
}
func (m *QueryBidResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBidResponse.Size(m)
}
func (m *QueryBidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBidResponse proto.InternalMessageInfo

func (m *QueryBidResponse) GetBid() Bid {
	if m != nil {
		return m.Bid
	}
	return Bid{}
}

// QueryLeasesRequest is request type for the Query/Leases RPC method
type QueryLeasesRequest struct {
	Filters              LeaseFilters       `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters"`
	Pagination           *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryLeasesRequest) Reset()         { *m = QueryLeasesRequest{} }
func (m *QueryLeasesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLeasesRequest) ProtoMessage()    {}
func (*QueryLeasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{8}
}
func (m *QueryLeasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLeasesRequest.Unmarshal(m, b)
}
func (m *QueryLeasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLeasesRequest.Marshal(b, m, deterministic)
}
func (m *QueryLeasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLeasesRequest.Merge(m, src)
}
func (m *QueryLeasesRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLeasesRequest.Size(m)
}
func (m *QueryLeasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLeasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLeasesRequest proto.InternalMessageInfo

func (m *QueryLeasesRequest) GetFilters() LeaseFilters {
	if m != nil {
		return m.Filters
	}
	return LeaseFilters{}
}

func (m *QueryLeasesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLeasesResponse is response type for the Query/Leases RPC method
type QueryLeasesResponse struct {
	Leases               []QueryLeaseResponse `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases"`
	Pagination           *query.PageResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryLeasesResponse) Reset()         { *m = QueryLeasesResponse{} }
func (m *QueryLeasesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLeasesResponse) ProtoMessage()    {}
func (*QueryLeasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{9}
}
func (m *QueryLeasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLeasesResponse.Unmarshal(m, b)
}
func (m *QueryLeasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLeasesResponse.Marshal(b, m, deterministic)
}
func (m *QueryLeasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLeasesResponse.Merge(m, src)
}
func (m *QueryLeasesResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLeasesResponse.Size(m)
}
func (m *QueryLeasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLeasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLeasesResponse proto.InternalMessageInfo

func (m *QueryLeasesResponse) GetLeases() []QueryLeaseResponse {
	if m != nil {
		return m.Leases
	}
	return nil
}

func (m *QueryLeasesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLeaseRequest is request type for the Query/Lease RPC method
type QueryLeaseRequest struct {
	ID                   LeaseID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLeaseRequest) Reset()         { *m = QueryLeaseRequest{} }
func (m *QueryLeaseRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLeaseRequest) ProtoMessage()    {}
func (*QueryLeaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{10}
}
func (m *QueryLeaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLeaseRequest.Unmarshal(m, b)
}
func (m *QueryLeaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLeaseRequest.Marshal(b, m, deterministic)
}
func (m *QueryLeaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLeaseRequest.Merge(m, src)
}
func (m *QueryLeaseRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLeaseRequest.Size(m)
}
func (m *QueryLeaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLeaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLeaseRequest proto.InternalMessageInfo

func (m *QueryLeaseRequest) GetID() LeaseID {
	if m != nil {
		return m.ID
	}
	return LeaseID{}
}

// QueryLeaseResponse is response type for the Query/Lease RPC method
type QueryLeaseResponse struct {
	Lease                Lease    `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLeaseResponse) Reset()         { *m = QueryLeaseResponse{} }
func (m *QueryLeaseResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLeaseResponse) ProtoMessage()    {}
func (*QueryLeaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_340dbe75bd35be3a, []int{11}
}
func (m *QueryLeaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLeaseResponse.Unmarshal(m, b)
}
func (m *QueryLeaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLeaseResponse.Marshal(b, m, deterministic)
}
func (m *QueryLeaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLeaseResponse.Merge(m, src)
}
func (m *QueryLeaseResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLeaseResponse.Size(m)
}
func (m *QueryLeaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLeaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLeaseResponse proto.InternalMessageInfo

func (m *QueryLeaseResponse) GetLease() Lease {
	if m != nil {
		return m.Lease
	}
	return Lease{}
}

func init() {
	proto.RegisterType((*QueryOrdersRequest)(nil), "subnet.k8s.market.v1.QueryOrdersRequest")
	proto.RegisterType((*QueryOrdersResponse)(nil), "subnet.k8s.market.v1.QueryOrdersResponse")
	proto.RegisterType((*QueryOrderRequest)(nil), "subnet.k8s.market.v1.QueryOrderRequest")
	proto.RegisterType((*QueryOrderResponse)(nil), "subnet.k8s.market.v1.QueryOrderResponse")
	proto.RegisterType((*QueryBidsRequest)(nil), "subnet.k8s.market.v1.QueryBidsRequest")
	proto.RegisterType((*QueryBidsResponse)(nil), "subnet.k8s.market.v1.QueryBidsResponse")
	proto.RegisterType((*QueryBidRequest)(nil), "subnet.k8s.market.v1.QueryBidRequest")
	proto.RegisterType((*QueryBidResponse)(nil), "subnet.k8s.market.v1.QueryBidResponse")
	proto.RegisterType((*QueryLeasesRequest)(nil), "subnet.k8s.market.v1.QueryLeasesRequest")
	proto.RegisterType((*QueryLeasesResponse)(nil), "subnet.k8s.market.v1.QueryLeasesResponse")
	proto.RegisterType((*QueryLeaseRequest)(nil), "subnet.k8s.market.v1.QueryLeaseRequest")
	proto.RegisterType((*QueryLeaseResponse)(nil), "subnet.k8s.market.v1.QueryLeaseResponse")
}

func init() { proto.RegisterFile("market/v1/query.proto", fileDescriptor_340dbe75bd35be3a) }

var fileDescriptor_340dbe75bd35be3a = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6b, 0xd4, 0x4e,
	0x18, 0xfe, 0x65, 0xdb, 0xee, 0x0f, 0xa6, 0xe0, 0x9f, 0x69, 0x85, 0xba, 0x55, 0xb6, 0x4d, 0xd5,
	0x6e, 0x0f, 0x66, 0x68, 0x3d, 0xb4, 0xde, 0x4a, 0xba, 0x16, 0x5b, 0xfc, 0xbb, 0x47, 0x6f, 0x49,
	0x33, 0x1b, 0x87, 0x4d, 0x33, 0xdb, 0x4c, 0x52, 0xf0, 0x20, 0x88, 0x20, 0x78, 0xf7, 0x24, 0x22,
	0x08, 0xde, 0xbc, 0xf8, 0x35, 0xbc, 0x7b, 0xaf, 0x20, 0x7e, 0x10, 0x99, 0x77, 0x26, 0x9b, 0xec,
	0x9a, 0x26, 0x29, 0xb4, 0xb7, 0x92, 0x79, 0x9f, 0x67, 0x9e, 0xf7, 0x7d, 0xe6, 0x79, 0xbb, 0xe8,
	0xda, 0xa1, 0x13, 0x0d, 0x68, 0x4c, 0x8e, 0xd7, 0xc9, 0x51, 0x42, 0xa3, 0x57, 0xd6, 0x30, 0xe2,
	0x31, 0xc7, 0xf3, 0x22, 0x71, 0x43, 0x1a, 0x5b, 0x83, 0x2d, 0x61, 0xa9, 0x0a, 0xeb, 0x78, 0xbd,
	0x35, 0xef, 0x73, 0x9f, 0x43, 0x01, 0x91, 0x7f, 0xa9, 0xda, 0xd6, 0x0d, 0x9f, 0x73, 0x3f, 0xa0,
	0xc4, 0x19, 0x32, 0xe2, 0x84, 0x21, 0x8f, 0x9d, 0x98, 0xf1, 0x50, 0xa4, 0xa7, 0x49, 0xcc, 0x02,
	0xa1, 0xc8, 0xc9, 0xd0, 0xf1, 0x59, 0x08, 0xc7, 0xfa, 0x34, 0x77, 0x3d, 0x8f, 0x3c, 0x1a, 0xe9,
	0xcf, 0x73, 0xd9, 0x67, 0x97, 0x79, 0xff, 0xd6, 0x06, 0xd4, 0x11, 0x54, 0x7d, 0x36, 0x3f, 0x1b,
	0x08, 0x3f, 0x97, 0xec, 0x4f, 0x25, 0x81, 0xe8, 0xd1, 0xa3, 0x84, 0x8a, 0x18, 0xdb, 0xe8, 0xff,
	0x3e, 0x0b, 0x62, 0x1a, 0x89, 0x05, 0x63, 0xc9, 0xe8, 0xcc, 0x6e, 0x98, 0x56, 0x51, 0x4f, 0x16,
	0xa0, 0x76, 0x55, 0xa5, 0x3d, 0xfd, 0xe3, 0xa4, 0xfd, 0x5f, 0x2f, 0x05, 0xe2, 0x1d, 0x84, 0x32,
	0xc5, 0x0b, 0x0d, 0xa0, 0x59, 0xc9, 0xd3, 0x40, 0x6f, 0x96, 0x1a, 0xdc, 0x33, 0xc7, 0xa7, 0xfa,
	0xf2, 0x5e, 0x0e, 0x66, 0x7e, 0x31, 0xd0, 0xdc, 0x98, 0x3e, 0x31, 0xe4, 0xa1, 0xa0, 0x78, 0x07,
	0x35, 0xa1, 0x65, 0xa9, 0x6f, 0xaa, 0x33, 0xbb, 0xb1, 0x58, 0xa2, 0xcf, 0xbe, 0x24, 0x85, 0x7d,
	0xfb, 0xd5, 0x6e, 0x6a, 0x12, 0x0d, 0xc5, 0xdd, 0x02, 0x85, 0xb7, 0xca, 0x15, 0xaa, 0xeb, 0xc7,
	0x24, 0x3e, 0x41, 0x57, 0x33, 0x85, 0xe9, 0x00, 0xef, 0xa3, 0x06, 0xf3, 0xf4, 0xec, 0x6e, 0x96,
	0x68, 0xdb, 0xeb, 0xda, 0x48, 0xaa, 0xfb, 0x7d, 0xd2, 0x6e, 0xec, 0x75, 0x7b, 0x0d, 0xe6, 0x99,
	0x8f, 0xf3, 0x8e, 0x8c, 0x1a, 0xde, 0x44, 0x33, 0xa0, 0x5a, 0x73, 0x96, 0xf6, 0xab, 0x8c, 0x50,
	0xf5, 0xe6, 0x47, 0x03, 0x5d, 0x01, 0x3e, 0x9b, 0x79, 0x23, 0x7f, 0xb7, 0x27, 0xfd, 0x5d, 0x2a,
	0xe6, 0xb3, 0x99, 0x77, 0x91, 0xee, 0x7e, 0x32, 0xf4, 0xec, 0x94, 0x36, 0xdd, 0xea, 0x36, 0x9a,
	0x76, 0x99, 0x97, 0x3a, 0x7b, 0xa7, 0x58, 0x59, 0x0a, 0x4b, 0x51, 0x5a, 0x1f, 0x20, 0xcf, 0xc9,
	0xd8, 0x7d, 0x74, 0x39, 0xbb, 0x45, 0xcd, 0x6d, 0x33, 0x67, 0xeb, 0xe2, 0xa9, 0x23, 0x2b, 0x30,
	0xf5, 0x41, 0x66, 0xc2, 0xa8, 0xcf, 0x75, 0x34, 0xe5, 0x8e, 0xd8, 0xae, 0x9f, 0xca, 0xa6, 0x3b,
	0x93, 0xb5, 0x59, 0x5c, 0x1f, 0xc9, 0x0c, 0x9f, 0x39, 0xae, 0x80, 0xba, 0x48, 0x43, 0xbf, 0xa6,
	0x71, 0x4d, 0xf5, 0xe9, 0x56, 0x77, 0x51, 0x13, 0xb6, 0x4e, 0x6a, 0x6a, 0xa7, 0xc4, 0x54, 0x80,
	0x4e, 0xd8, 0xaa, 0xd1, 0xe7, 0x9c, 0x58, 0x7d, 0x53, 0xed, 0xc4, 0x42, 0x7d, 0x49, 0x62, 0xc7,
	0x94, 0xcb, 0xc4, 0x82, 0xea, 0xf2, 0xe7, 0x02, 0x98, 0x34, 0xb1, 0x50, 0xbf, 0xf1, 0xbd, 0x89,
	0x66, 0x80, 0x0f, 0xbf, 0x37, 0x90, 0xde, 0x59, 0xb8, 0x6c, 0x62, 0x63, 0xbb, 0xbb, 0xb5, 0x56,
	0xa3, 0x52, 0x49, 0x34, 0xd7, 0xde, 0xfe, 0xfc, 0xf3, 0xa1, 0xb1, 0x82, 0x97, 0x89, 0x82, 0x90,
	0xc1, 0x96, 0x20, 0x13, 0xff, 0x54, 0x04, 0x09, 0x98, 0x88, 0xf1, 0x3b, 0x03, 0xcd, 0x00, 0x1a,
	0xaf, 0x56, 0xf1, 0xa7, 0x42, 0x3a, 0xd5, 0x85, 0x67, 0xd2, 0xc1, 0xc2, 0x3e, 0xc7, 0x6f, 0x0c,
	0x34, 0x2d, 0xb7, 0x05, 0xae, 0xd8, 0x0b, 0xa3, 0x71, 0xac, 0x56, 0xd6, 0x69, 0x11, 0xab, 0x20,
	0x62, 0x19, 0xb7, 0x8b, 0x45, 0xc8, 0xc5, 0xa2, 0x46, 0xf1, 0x1a, 0x4d, 0xd9, 0xcc, 0xc3, 0xb7,
	0xab, 0x16, 0x93, 0xba, 0xbf, 0xe6, 0xfe, 0xaa, 0x75, 0x3d, 0x4c, 0x40, 0x3e, 0x0a, 0x15, 0x2f,
	0x5c, 0x19, 0xa3, 0x5a, 0x8f, 0x62, 0x3c, 0xab, 0x55, 0x66, 0xa8, 0x24, 0x66, 0x8f, 0x02, 0xd0,
	0xa5, 0x8f, 0x22, 0x1f, 0xb3, 0x56, 0xed, 0xe4, 0xd7, 0xd4, 0x21, 0x47, 0x62, 0xef, 0xbf, 0x78,
	0xe8, 0xb3, 0xf8, 0x65, 0xe2, 0x5a, 0x07, 0xfc, 0x90, 0x24, 0x21, 0x3b, 0xe0, 0x51, 0x98, 0x04,
	0x71, 0xe4, 0xf4, 0x79, 0x12, 0x7a, 0x90, 0x7a, 0xcd, 0x72, 0x37, 0xe4, 0x1e, 0x25, 0xea, 0x67,
	0x58, 0x11, 0xaf, 0xdb, 0x84, 0xb3, 0x7b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xea, 0xca, 0xac,
	0x39, 0xdc, 0x09, 0x00, 0x00,
}
