syntax = "proto3";
package subnet.k8s.base.v1;

import "gogoproto/gogo.proto";
import "base/v1/attribute.proto";
import "base/v1/resourcevalue.proto";

option go_package = "github.com/unicornultrafoundation/subnet-node/proto/subnet/k8s/base/v1";

// GPU stores resource units and cpu config attributes
message GPU {
  option (gogoproto.equal)      = true;
  ResourceValue      units      = 1 [
    (gogoproto.nullable) = false
  ];
  repeated Attribute attributes = 2 [
    (gogoproto.nullable) = false,
    (gogoproto.castrepeated) = "Attributes",
    (gogoproto.jsontag)  = "attributes,omitempty",
    (gogoproto.moretags) = "yaml:\"attributes,omitempty\""
  ];
}
