// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: provider/lease/v1/service.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaseRPC_SendManifest_FullMethodName        = "/subnet.k8s.provider.lease.v1.LeaseRPC/SendManifest"
	LeaseRPC_ServiceStatus_FullMethodName       = "/subnet.k8s.provider.lease.v1.LeaseRPC/ServiceStatus"
	LeaseRPC_StreamServiceStatus_FullMethodName = "/subnet.k8s.provider.lease.v1.LeaseRPC/StreamServiceStatus"
	LeaseRPC_ServiceLogs_FullMethodName         = "/subnet.k8s.provider.lease.v1.LeaseRPC/ServiceLogs"
	LeaseRPC_StreamServiceLogs_FullMethodName   = "/subnet.k8s.provider.lease.v1.LeaseRPC/StreamServiceLogs"
)

// LeaseRPCClient is the client API for LeaseRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LeaseRPC defines the RPC server for lease control
type LeaseRPCClient interface {
	// SendManifest sends manifest to the provider
	SendManifest(ctx context.Context, in *SendManifestRequest, opts ...grpc.CallOption) (*SendManifestResponse, error)
	// ServiceStatus
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error)
	// StreamServiceStatus
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceStatusResponse], error)
	// ServiceLogs
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (*ServiceLogsResponse, error)
	// StreamServiceLogs
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceLogsResponse], error)
}

type leaseRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaseRPCClient(cc grpc.ClientConnInterface) LeaseRPCClient {
	return &leaseRPCClient{cc}
}

func (c *leaseRPCClient) SendManifest(ctx context.Context, in *SendManifestRequest, opts ...grpc.CallOption) (*SendManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendManifestResponse)
	err := c.cc.Invoke(ctx, LeaseRPC_SendManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseRPCClient) ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatusResponse)
	err := c.cc.Invoke(ctx, LeaseRPC_ServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseRPCClient) StreamServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeaseRPC_ServiceDesc.Streams[0], LeaseRPC_StreamServiceStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceStatusRequest, ServiceStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseRPC_StreamServiceStatusClient = grpc.ServerStreamingClient[ServiceStatusResponse]

func (c *leaseRPCClient) ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (*ServiceLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceLogsResponse)
	err := c.cc.Invoke(ctx, LeaseRPC_ServiceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseRPCClient) StreamServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeaseRPC_ServiceDesc.Streams[1], LeaseRPC_StreamServiceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceLogsRequest, ServiceLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseRPC_StreamServiceLogsClient = grpc.ServerStreamingClient[ServiceLogsResponse]

// LeaseRPCServer is the server API for LeaseRPC service.
// All implementations must embed UnimplementedLeaseRPCServer
// for forward compatibility.
//
// LeaseRPC defines the RPC server for lease control
type LeaseRPCServer interface {
	// SendManifest sends manifest to the provider
	SendManifest(context.Context, *SendManifestRequest) (*SendManifestResponse, error)
	// ServiceStatus
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error)
	// StreamServiceStatus
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamServiceStatus(*ServiceStatusRequest, grpc.ServerStreamingServer[ServiceStatusResponse]) error
	// ServiceLogs
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ServiceLogs(context.Context, *ServiceLogsRequest) (*ServiceLogsResponse, error)
	// StreamServiceLogs
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[ServiceLogsResponse]) error
	mustEmbedUnimplementedLeaseRPCServer()
}

// UnimplementedLeaseRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaseRPCServer struct{}

func (UnimplementedLeaseRPCServer) SendManifest(context.Context, *SendManifestRequest) (*SendManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendManifest not implemented")
}
func (UnimplementedLeaseRPCServer) ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceStatus not implemented")
}
func (UnimplementedLeaseRPCServer) StreamServiceStatus(*ServiceStatusRequest, grpc.ServerStreamingServer[ServiceStatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamServiceStatus not implemented")
}
func (UnimplementedLeaseRPCServer) ServiceLogs(context.Context, *ServiceLogsRequest) (*ServiceLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceLogs not implemented")
}
func (UnimplementedLeaseRPCServer) StreamServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[ServiceLogsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamServiceLogs not implemented")
}
func (UnimplementedLeaseRPCServer) mustEmbedUnimplementedLeaseRPCServer() {}
func (UnimplementedLeaseRPCServer) testEmbeddedByValue()                  {}

// UnsafeLeaseRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaseRPCServer will
// result in compilation errors.
type UnsafeLeaseRPCServer interface {
	mustEmbedUnimplementedLeaseRPCServer()
}

func RegisterLeaseRPCServer(s grpc.ServiceRegistrar, srv LeaseRPCServer) {
	// If the following call pancis, it indicates UnimplementedLeaseRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaseRPC_ServiceDesc, srv)
}

func _LeaseRPC_SendManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseRPCServer).SendManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseRPC_SendManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseRPCServer).SendManifest(ctx, req.(*SendManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseRPC_ServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseRPCServer).ServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseRPC_ServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseRPCServer).ServiceStatus(ctx, req.(*ServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseRPC_StreamServiceStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeaseRPCServer).StreamServiceStatus(m, &grpc.GenericServerStream[ServiceStatusRequest, ServiceStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseRPC_StreamServiceStatusServer = grpc.ServerStreamingServer[ServiceStatusResponse]

func _LeaseRPC_ServiceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseRPCServer).ServiceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseRPC_ServiceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseRPCServer).ServiceLogs(ctx, req.(*ServiceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseRPC_StreamServiceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeaseRPCServer).StreamServiceLogs(m, &grpc.GenericServerStream[ServiceLogsRequest, ServiceLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseRPC_StreamServiceLogsServer = grpc.ServerStreamingServer[ServiceLogsResponse]

// LeaseRPC_ServiceDesc is the grpc.ServiceDesc for LeaseRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaseRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subnet.k8s.provider.lease.v1.LeaseRPC",
	HandlerType: (*LeaseRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendManifest",
			Handler:    _LeaseRPC_SendManifest_Handler,
		},
		{
			MethodName: "ServiceStatus",
			Handler:    _LeaseRPC_ServiceStatus_Handler,
		},
		{
			MethodName: "ServiceLogs",
			Handler:    _LeaseRPC_ServiceLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamServiceStatus",
			Handler:       _LeaseRPC_StreamServiceStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamServiceLogs",
			Handler:       _LeaseRPC_StreamServiceLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider/lease/v1/service.proto",
}
