name: Build Golang for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: go mod tidy

      # Step 4: Build the executable
      - name: Build Executable
        run: |
          go build -o subnet-windows-amd64.exe cmd/subnet/main.go

      # Step 5: Archive the executable (optional)
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: subnet-windows-amd64
          path: subnet-windows-amd64.exe
