name: Build and Release (Linux)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build for Linux
        run: |
          NAME="subnet"
          PLATFORMS=("linux/amd64" "linux/arm64")
          mkdir -p dist
          for PLATFORM in "${PLATFORMS[@]}"; do
            OS=${PLATFORM%/*}
            ARCH=${PLATFORM#*/}
            OUTPUT="dist/${NAME}-${VERSION}-${OS}-${ARCH}"
            GOOS=$OS GOARCH=$ARCH CGO_ENABLED=0 go build -ldflags "-X 'github.com/unicornultrafoundation/subnet-node.CurrentCommit=$(git rev-parse HEAD)' -X 'github.com/unicornultrafoundation/subnet-node.CurrentVersionNumber=${VERSION}'" -o $OUTPUT ./cmd/subnet/main.go
          done

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: dist/

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
